// ABE - Vehicle Component Damage Model
//
// Evaluates post-penetration damage to vehicle components: ammo rack cookoff,
// fuel tank fire/explosion, engine kill/fire, transmission damage, and
// crew incapacitation from behind-armour debris (BAD / spall).
//
// Called after a projectile has perforated the main armour — the caller
// provides residual velocity, energy, spall/BAD data, and the component
// configuration.
//
// References:
//   - MIL-HDBK-799 (Vehicle Vulnerability — Component Kill Criteria)
//   - BRL CR 341 (Critical Energy Criteria for Vehicle Components)
//   - NATO STANAG 4569 Annex D (Crew Vulnerability to Spall)
//   - Fairlie J.P., "Behind Armour Debris Modelling" (DERA)
//   - DMSS (Defence Modelling & Simulation) Handbook, UK MoD
//   - Held M., "Cookoff Thresholds for Stored Munitions" (Propellants,
//     Explosives, Pyrotechnics, Vol 15)
//   - MIL-STD-2105D (Hazard Assessment for Ammunition Stowage)

// Re-export public items from submodules to maintain the original public API.
// These types were previously defined directly in this module.
pub use super::crew_injury::{
    BodyRegion, BodyRegionInjury, CrewInjuryResult, InjurySeverity, evaluate_crew_refined,
};
pub use super::fire_propagation::{
    ComponentFireState, FirePropagationResult, FireStatus, FireSuppression, damage_to_fire_state,
    evaluate_fire_propagation,
};

use super::crew_injury::rand_threshold;

// ── Component & stored-material types ──────────────────────────────────────────

/// Types of ammunition stored in a vehicle component.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum AmmoStoredType {
    /// Small-arms cartridges (5.56, 7.62, 12.7 mm) — cookoff ~5 kJ threshold.
    SmallArms,
    /// Cannon shells (20–40 mm HE/I) — cookoff ~20 kJ.
    CannonShells,
    /// Shaped-charge warheads (ATGM, HEAT) — cookoff ~1 kJ (sensitive explosive).
    HEAT,
    /// Missile rocket motors (stored propellant) — cookoff ~10 kJ.
    Missile,
    /// Mixed stowage — uses the lowest threshold present.
    Mixed,
}

/// Fuel types carried in vehicle fuel tanks.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum FuelType {
    /// Diesel — low volatility, hardest to ignite.
    Diesel,
    /// Petrol (gasoline) — high volatility, easiest to ignite.
    Petrol,
    /// JP-8 / kerosene-based turbine fuel — intermediate.
    JP8,
}

/// Engine type — determines block mass and fire behaviour.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum EngineType {
    /// Heavy diesel engine (armoured vehicles, ~800 kg).
    Diesel,
    /// Petrol engine (light vehicles, ~200 kg).
    Petrol,
    /// Gas turbine (MBTs, ~600 kg).
    Turbine,
    /// Electric motor (hybrid/EVs, ~150 kg).
    Electric,
}

/// Protection level for crew positions behind armour.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CrewProtection {
    /// Unprotected — bare steel behind armour, no spall liner.
    None,
    /// Light liner — thin Kevlar/twaron sheet.
    Light,
    /// Full spall liner — thick aramid or UHMWPE layer.
    SpallLiner,
    /// Heavy protection — encapsulated crew pod with spaced armour.
    Heavy,
}

/// Vehicle component type — the high-level discriminator.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ComponentType {
    /// Ammunition stowage (ready-rack, hull stowage).
    AmmoRack { ammo_type: AmmoStoredType },
    /// Fuel tank (integral, armoured, or external).
    FuelTank { fuel_type: FuelType },
    /// Engine / powerpack.
    Engine { engine_type: EngineType },
    /// Gearbox / final drive.
    Transmission,
    /// Crew position (driver, gunner, commander, loader).
    Crew { protection_level: CrewProtection },
}

// ── Configuration & result structs ────────────────────────────────────────────

/// Configuration describing a single vehicle component.
#[derive(Debug, Clone)]
pub struct ComponentConfig {
    /// Which component and its sub-type.
    pub component: ComponentType,
    /// Local armour protection thickness in mm (0 if unarmoured).
    pub local_armor_thickness_mm: f64,
    /// Armour material type (same strings as penetration::material_factor).
    pub local_armor_material: &'static str,
    /// Local armour angle from normal in degrees (0 = perpendicular).
    pub local_angle_deg: f64,
}

/// Result of evaluating post-penetration damage to a vehicle component.
#[derive(Debug, Clone)]
pub struct ComponentDamageResult {
    /// Component has been completely destroyed (e.g. ammo cookoff).
    pub component_destroyed: bool,
    /// Component is disabled (fuel tank leaking, engine seized).
    pub component_disabled: bool,
    /// A fire has started in this component.
    pub fire_started: bool,
    /// The component has exploded (ammo cookoff or fuel vapour explosion).
    pub explosion: bool,
    /// Number of secondary fragments generated by this component failure
    /// (e.g. ammo rack fragments, flywheel fragments).
    pub secondary_fragments: i32,
    /// Residual kinetic energy of the projectile after damaging this
    /// component (it may continue into adjacent components).
    pub residual_energy_j: f64,
    /// Fraction of vehicle mobility lost due to this damage (0.0–1.0).
    pub mobility_loss_fraction: f64,
    /// Number of crew casualties in this crew position.
    pub crew_casualties: i32,
}

// ── Cookoff thresholds ─────────────────────────────────────────────────────────

/// Cookoff energy thresholds by ammo type (J).
fn cookoff_threshold_j(ammo: AmmoStoredType) -> f64 {
    match ammo {
        AmmoStoredType::SmallArms => 5_000.0,
        AmmoStoredType::CannonShells => 20_000.0,
        AmmoStoredType::HEAT => 1_000.0,
        AmmoStoredType::Missile => 10_000.0,
        // Mixed: use the lowest to be conservative
        AmmoStoredType::Mixed => 1_000.0,
    }
}

/// Scale factor for ammo type sensitivity to cookoff (higher = more sensitive).
fn cookoff_sensitivity(ammo: AmmoStoredType) -> f64 {
    match ammo {
        AmmoStoredType::SmallArms => 1.0,
        AmmoStoredType::CannonShells => 0.8,
        AmmoStoredType::HEAT => 2.0,
        AmmoStoredType::Missile => 1.5,
        AmmoStoredType::Mixed => 1.2,
    }
}

// ── Fuel ignition thresholds ──────────────────────────────────────────────────

/// Minimum residual energy to start a fuel leak (J).
const FUEL_LEAK_THRESHOLD_J: f64 = 200.0;

/// Energy threshold for fuel vapour explosion (above leak threshold).
fn fuel_explosion_threshold_j(fuel: FuelType) -> f64 {
    match fuel {
        FuelType::Petrol => 2_000.0,
        FuelType::JP8 => 5_000.0,
        FuelType::Diesel => 8_000.0,
    }
}

/// Base probability of fire per kJ of residual energy, without incendiary.
fn fuel_fire_base_prob(fuel: FuelType) -> f64 {
    match fuel {
        FuelType::Petrol => 0.08,
        FuelType::JP8 => 0.04,
        FuelType::Diesel => 0.02,
    }
}

// ── Engine constants ──────────────────────────────────────────────────────────

/// Engine block mass (kg) by type — used to compute energy absorption.
fn engine_block_mass_kg(engine: EngineType) -> f64 {
    match engine {
        EngineType::Diesel => 800.0,
        EngineType::Petrol => 200.0,
        EngineType::Turbine => 600.0,
        EngineType::Electric => 150.0,
    }
}

/// Engine fire base probability (per kJ of absorbed energy).
fn engine_fire_prob(engine: EngineType) -> f64 {
    match engine {
        EngineType::Diesel => 0.01,
        EngineType::Petrol => 0.05,
        EngineType::Turbine => 0.03,
        EngineType::Electric => 0.005,
    }
}

// ── Crew vulnerability constants ──────────────────────────────────────────────

/// Spall liner protection factor (multiplier on fragment kinetic energy
/// required to cause injury).
pub(crate) fn spall_protection_factor(protection: CrewProtection) -> f64 {
    match protection {
        CrewProtection::None => 1.0,
        CrewProtection::Light => 2.5,
        CrewProtection::SpallLiner => 5.0,
        CrewProtection::Heavy => 10.0,
    }
}

/// Minimum fragment KE (J) to cause a crew casualty.
pub(crate) const CREW_INJURY_THRESHOLD_J: f64 = 80.0;

// ── Projectile type modifiers ─────────────────────────────────────────────────

/// Fire multiplier: incendiary and API rounds increase fire probability.
fn projectile_fire_multiplier(proj_type: &str) -> f64 {
    match proj_type.to_lowercase().as_str() {
        "incendiary" | "i" => 3.0,
        "api" | "ap_i" => 2.5,
        "hei" | "he_i" => 4.0,
        "hei_t" | "he_i_t" => 4.0,
        "tracer" | "t" | "t45" | "t46" => 1.3,
        _ => 1.0,
    }
}

/// Fragmentation multiplier: some rounds produce more secondary fragments.
fn projectile_frag_multiplier(proj_type: &str) -> f64 {
    match proj_type.to_lowercase().as_str() {
        "incendiary" | "i" => 1.5,
        "api" | "ap_i" => 1.3,
        "hei" | "he_i" => 2.0,
        "hei_t" | "he_i_t" => 2.0,
        "heat" | "he" => 1.8,
        _ => 1.0,
    }
}

// ── Core evaluation ───────────────────────────────────────────────────────────

/// Evaluate damage to a vehicle component after armour penetration.
///
/// # Arguments
/// * `component` — The component configuration (type, local armour, material).
/// * `residual_velocity_ms` — Projectile velocity after penetrating the
///   vehicle's main armour (m/s).  Pass 0.0 if the round did not penetrate.
/// * `projectile_mass_g` — Projectile mass in grams.
/// * `projectile_type` — Construction type string: "ball", "ap", "apds",
///   "incendiary", "api", "hei", "tracer", etc.
/// * `caliber_mm` — Projectile calibre in millimetres.
/// * `spall_fragments` — Number of behind-armour debris (BAD) fragments
///   from the armour penetration (use `PenetrationResult.spall_fragments`).
/// * `bad_spray_angle_deg` — Spray cone half-angle of BAD fragments
///   (use `PenetrationResult.bad_spray_angle_deg`).
/// * `bad_total_mass_g` — Total mass of BAD fragments
///   (use `PenetrationResult.bad_total_mass_g`).
///
/// # Returns
/// `ComponentDamageResult` describing the damage state.
#[allow(clippy::too_many_arguments)]
// ponytail: physics kernel, all params required
pub fn evaluate_component_damage(
    component: &ComponentConfig,
    residual_velocity_ms: f64,
    projectile_mass_g: f64,
    projectile_type: &str,
    caliber_mm: f64,
    spall_fragments: i32,
    bad_spray_angle_deg: f64,
    bad_total_mass_g: f64,
) -> ComponentDamageResult {
    // Compute residual kinetic energy
    let mass_kg = projectile_mass_g / 1000.0;
    let residual_ke_j = 0.5 * mass_kg * residual_velocity_ms.powi(2);

    // If residual velocity is below threshold, no meaningful damage
    if residual_velocity_ms < 50.0 && spall_fragments == 0 {
        return ComponentDamageResult {
            component_destroyed: false,
            component_disabled: false,
            fire_started: false,
            explosion: false,
            secondary_fragments: 0,
            residual_energy_j: residual_ke_j,
            mobility_loss_fraction: 0.0,
            crew_casualties: 0,
        };
    }

    let proj_mult = projectile_fire_multiplier(projectile_type);
    let frag_mult = projectile_frag_multiplier(projectile_type);

    match component.component {
        ComponentType::AmmoRack { ammo_type } => evaluate_ammo_rack(
            ammo_type,
            residual_ke_j,
            residual_velocity_ms,
            caliber_mm,
            proj_mult,
            frag_mult,
        ),
        ComponentType::FuelTank { fuel_type } => evaluate_fuel_tank(
            fuel_type,
            residual_ke_j,
            residual_velocity_ms,
            component,
            proj_mult,
            frag_mult,
        ),
        ComponentType::Engine { engine_type } => {
            evaluate_engine(engine_type, residual_ke_j, residual_velocity_ms, proj_mult)
        },
        ComponentType::Transmission => {
            evaluate_transmission(residual_ke_j, residual_velocity_ms, caliber_mm)
        },
        ComponentType::Crew { protection_level } => evaluate_crew(
            protection_level,
            residual_ke_j,
            residual_velocity_ms,
            spall_fragments,
            bad_spray_angle_deg,
            bad_total_mass_g,
            caliber_mm,
        ),
    }
}

// ── Per-component evaluators ───────────────────────────────────────────────────

/// Evaluate ammo rack cookoff.
fn evaluate_ammo_rack(
    ammo_type: AmmoStoredType,
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    _caliber_mm: f64,
    proj_mult: f64,
    frag_mult: f64,
) -> ComponentDamageResult {
    let threshold = cookoff_threshold_j(ammo_type);
    let sensitivity = cookoff_sensitivity(ammo_type);

    if residual_ke_j < threshold {
        // Not enough energy for cookoff — projectile passes through
        // with partial energy absorption from internal structure.
        let absorbed_frac = 0.1;
        return ComponentDamageResult {
            component_destroyed: false,
            component_disabled: false,
            fire_started: false,
            explosion: false,
            secondary_fragments: (2.0 * frag_mult) as i32,
            residual_energy_j: residual_ke_j * (1.0 - absorbed_frac),
            mobility_loss_fraction: 0.0,
            crew_casualties: 0,
        };
    }

    // Energy above threshold: probability of cookoff scales with
    // energy density and sensitivity.
    let energy_ratio = (residual_ke_j / threshold).clamp(1.0, 10.0);
    let cookoff_prob = (1.0 - (-sensitivity * (energy_ratio - 1.0)).exp()).clamp(0.0, 1.0);

    // If cookoff occurs, it's a catastrophic high-order explosion.
    let explosion = rand_threshold(cookoff_prob);

    if explosion {
        // Catastrophic cookoff: all residual energy released as explosion.
        // Secondary fragments from ammo cases, links, vehicle structure.
        let frag_count = (50.0 * frag_mult + 30.0 * (energy_ratio - 1.0)).round() as i32;
        ComponentDamageResult {
            component_destroyed: true,
            component_disabled: true,
            fire_started: true,
            explosion: true,
            secondary_fragments: frag_count.clamp(10, 200),
            residual_energy_j: residual_ke_j * 0.05, // almost none left
            mobility_loss_fraction: 1.0,
            crew_casualties: 0,
        }
    } else {
        // No cookoff, but ammo may be damaged / burning propellant.
        // ponytail: simple fire check, revisit with stowed-round cookoff model
        let fire_prob = 0.05 * proj_mult * sensitivity * (energy_ratio - 1.0).min(1.0);
        let fire = rand_threshold(fire_prob.clamp(0.0, 1.0));
        ComponentDamageResult {
            component_destroyed: false,
            component_disabled: fire,
            fire_started: fire,
            explosion: false,
            secondary_fragments: (5.0 * frag_mult) as i32,
            residual_energy_j: residual_ke_j * 0.7,
            mobility_loss_fraction: 0.0,
            crew_casualties: 0,
        }
    }
}

/// Evaluate fuel tank penetration.
fn evaluate_fuel_tank(
    fuel_type: FuelType,
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    component: &ComponentConfig,
    proj_mult: f64,
    frag_mult: f64,
) -> ComponentDamageResult {
    if residual_ke_j < FUEL_LEAK_THRESHOLD_J {
        // Projectile failed to perforate tank wall.
        return ComponentDamageResult {
            component_destroyed: false,
            component_disabled: false,
            fire_started: false,
            explosion: false,
            secondary_fragments: 0,
            residual_energy_j: residual_ke_j,
            mobility_loss_fraction: 0.0,
            crew_casualties: 0,
        };
    }

    // Fuel tank is always leaking if perforated (fuel is liquid).
    // The question is whether it ignites.
    let explosion_threshold = fuel_explosion_threshold_j(fuel_type);
    let base_prob = fuel_fire_base_prob(fuel_type);

    // Energy scaling: more energy → higher fire probability.
    let energy_factor = (residual_ke_j / 1000.0).clamp(1.0, 20.0);
    let fire_prob = (base_prob * energy_factor * proj_mult).clamp(0.0, 1.0);
    let fire = rand_threshold(fire_prob);

    // Explosion occurs if residual energy is well above threshold AND
    // fuel type is volatile enough. Fuel vapour explosion is a separate
    // event from fire (higher threshold).
    let explosion_prob = if residual_ke_j >= explosion_threshold {
        let vapor_ratio = ((residual_ke_j - explosion_threshold) / 10_000.0).clamp(0.0, 3.0);
        (0.15 * vapor_ratio * proj_mult).clamp(0.0, 0.9)
    } else {
        0.0
    };
    let explosion = rand_threshold(explosion_prob);

    // Energy absorption: fuel tank wall and fuel itself absorb some energy.
    let armor = component.local_armor_thickness_mm.max(1.0);
    let absorbed_by_tank = (armor * 10.0).min(residual_ke_j * 0.3);
    let residual = residual_ke_j - absorbed_by_tank;

    let frag_count = if explosion {
        (20.0 * frag_mult) as i32
    } else if fire {
        (5.0 * frag_mult) as i32
    } else {
        (2.0 * frag_mult) as i32
    };

    // Fuel tank is leaking whenever perforated (residual energy above
    // leak threshold).  Leaking fuel always disables the tank — the
    // question is only whether it ignites or explodes.
    let leaking = true;
    ComponentDamageResult {
        component_destroyed: explosion,
        component_disabled: leaking || fire || explosion,
        fire_started: fire || explosion,
        explosion,
        secondary_fragments: frag_count,
        residual_energy_j: residual.max(0.0),
        mobility_loss_fraction: if explosion { 1.0 } else { 0.0 },
        crew_casualties: 0,
    }
}

/// Evaluate engine damage.
fn evaluate_engine(
    engine_type: EngineType,
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    proj_mult: f64,
) -> ComponentDamageResult {
    let block_mass = engine_block_mass_kg(engine_type);

    // Energy absorbed by engine block. The block absorbs energy through
    // plastic deformation, cracking, and component damage.
    // ponytail: linear energy absorption model, upgrade to section-based
    // (cylinder head → block → crankcase) if per-system kill matters.
    let max_absorbed_j = block_mass * 150.0; // ~120 kJ for 800 kg diesel
    let absorbed_j = residual_ke_j.min(max_absorbed_j);
    let absorbed_fraction = absorbed_j / max_absorbed_j;

    // Gradual degradation: mobility loss scales with absorbed fraction.
    // Partial power loss kicks in before full kill.
    let mobility_loss = if absorbed_fraction < 0.15 {
        // Minor damage — some power loss
        absorbed_fraction * 0.5
    } else if absorbed_fraction < 0.40 {
        // Moderate damage — significant power loss, possible seize
        0.3 + (absorbed_fraction - 0.15) * 1.2
    } else {
        // Severe damage — engine stopped or seized
        let severe = 0.6 + (absorbed_fraction - 0.40) * 1.0;
        severe.min(1.0)
    };

    let disabled = absorbed_fraction >= 0.40;
    let destroyed = absorbed_fraction >= 0.85;

    // Fire from fuel/oil ignition on hot engine surfaces.
    let fire_prob = if absorbed_fraction > 0.2 {
        (engine_fire_prob(engine_type) * absorbed_fraction * 10.0 * proj_mult).clamp(0.0, 0.6)
    } else {
        0.0
    };
    let fire = rand_threshold(fire_prob);

    // Residual energy after passing through engine:
    // The projectile loses energy proportional to what the block absorbs.
    let residual = (residual_ke_j - absorbed_j).max(0.0);

    // Secondary fragments: flywheel / casing fragments if destroyed.
    let frags = if destroyed {
        15
    } else if absorbed_fraction > 0.3 {
        5
    } else {
        0
    };

    ComponentDamageResult {
        component_destroyed: destroyed,
        component_disabled: disabled,
        fire_started: fire,
        explosion: false,
        secondary_fragments: frags,
        residual_energy_j: residual,
        mobility_loss_fraction: mobility_loss,
        crew_casualties: 0,
    }
}

/// Evaluate transmission damage.
fn evaluate_transmission(
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    _caliber_mm: f64,
) -> ComponentDamageResult {
    // Transmission is compact with heavy gear clusters.
    // ponytail: single-box model, upgrade to gear-by-gear if individual
    // gear ratios matter.
    let max_absorbed_j = 60_000.0; // ~60 kJ to disable gearbox
    let absorbed_j = residual_ke_j.min(max_absorbed_j);
    let absorbed_fraction = absorbed_j / max_absorbed_j;

    let disabled = absorbed_fraction >= 0.35;
    let destroyed = absorbed_fraction >= 0.75;

    let mobility_loss = if destroyed {
        1.0
    } else if disabled {
        0.8
    } else {
        absorbed_fraction * 0.5
    };

    let residual = (residual_ke_j - absorbed_j).max(0.0);

    ComponentDamageResult {
        component_destroyed: destroyed,
        component_disabled: disabled,
        fire_started: false,
        explosion: false,
        secondary_fragments: if destroyed { 10 } else { 0 },
        residual_energy_j: residual,
        mobility_loss_fraction: mobility_loss,
        crew_casualties: 0,
    }
}

/// Evaluate crew injury from behind-armour debris (BAD / spall).
fn evaluate_crew(
    protection_level: CrewProtection,
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    spall_fragments: i32,
    bad_spray_angle_deg: f64,
    bad_total_mass_g: f64,
    _caliber_mm: f64,
) -> ComponentDamageResult {
    let protection = spall_protection_factor(protection_level);

    // Effective fragment KE = total BAD mass kinetic energy / fragment count,
    // reduced by spall liner protection.
    if spall_fragments <= 0 || bad_total_mass_g <= 0.0 {
        // No BAD fragments, but the projectile itself may still hit crew.
        // ponytail: direct projectile hit on crew — full KE, no spall
        return ComponentDamageResult {
            component_destroyed: false,
            component_disabled: false,
            fire_started: false,
            explosion: false,
            secondary_fragments: 0,
            residual_energy_j: residual_ke_j,
            mobility_loss_fraction: 0.0,
            crew_casualties: if residual_ke_j > CREW_INJURY_THRESHOLD_J {
                1
            } else {
                0
            },
        };
    }

    // BAD fragments distribute total mass. Average fragment KE:
    let avg_frag_mass_kg = bad_total_mass_g / spall_fragments as f64 / 1000.0;
    // Fragment velocity is approximately the residual velocity of the
    // projectile, reduced by spray angle spreading.
    let vel_factor = (bad_spray_angle_deg.max(5.0) / 45.0).clamp(0.2, 1.0);
    let frag_vel = _residual_velocity_ms * vel_factor.max(100.0 / _residual_velocity_ms.max(100.0));

    // Each fragment's kinetic energy, divided by protection factor.
    let frag_ke_j = 0.5 * avg_frag_mass_kg * frag_vel.powi(2) / protection;

    // Number of casualties: fragments that exceed injury threshold.
    let casualties = if frag_ke_j > CREW_INJURY_THRESHOLD_J {
        // Higher KE → more fragments cause injury.
        let inj_prob = (1.0 - CREW_INJURY_THRESHOLD_J / frag_ke_j).clamp(0.0, 1.0);
        (spall_fragments as f64 * inj_prob).round() as i32
    } else {
        // Fragments below threshold may still cause minor injury.
        // Only count ~10% as casualties if near threshold.
        if frag_ke_j > CREW_INJURY_THRESHOLD_J * 0.5 {
            1
        } else {
            0
        }
    };

    // Crew compartment is not "destroyed" but the crew position is
    // effectively disabled if all occupants are casualties.
    let position_disabled = casualties >= 1;

    ComponentDamageResult {
        component_destroyed: false,
        component_disabled: position_disabled,
        fire_started: false,
        explosion: false,
        secondary_fragments: 0,
        residual_energy_j: residual_ke_j * 0.9, // crew absorbs little energy
        mobility_loss_fraction: 0.0,
        crew_casualties: casualties.min(3), // max 3 per crew position
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Helpers ─────────────────────────────────────────────────────────────────

    /// Create a default component config for a given component type with
    /// the local armour parameters zeroed (unarmoured stowage).
    fn cfg(c: ComponentType) -> ComponentConfig {
        ComponentConfig {
            component: c,
            local_armor_thickness_mm: 0.0,
            local_armor_material: "steel_structural",
            local_angle_deg: 0.0,
        }
    }

    /// Quick damage evaluation with just the essential fields.
    fn eval(
        c: &ComponentConfig,
        res_vel: f64,
        mass_g: f64,
        proj_type: &str,
    ) -> ComponentDamageResult {
        evaluate_component_damage(c, res_vel, mass_g, proj_type, 7.62, 0, 0.0, 0.0)
    }

    /// Evaluate with BAD fragment data.
    fn eval_bad(
        c: &ComponentConfig,
        res_vel: f64,
        mass_g: f64,
        proj_type: &str,
        cal_mm: f64,
        spall: i32,
        spray_deg: f64,
        bad_mass_g: f64,
    ) -> ComponentDamageResult {
        evaluate_component_damage(
            c, res_vel, mass_g, proj_type, cal_mm, spall, spray_deg, bad_mass_g,
        )
    }

    // ── Ammo rack tests ─────────────────────────────────────────────────────────

    #[test]
    fn ammo_rack_small_arms_threshold_just_below() {
        // 4g projectile at 50 m/s → 0.5 * 0.004 * 50^2 = 5 J → below 5 kJ threshold
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::SmallArms,
        });
        let r = eval(&c, 50.0, 4.0, "ball");
        assert!(!r.explosion, "no cookoff below threshold");
        // At 5J vs 5000J threshold, energy is far below
        // ponytail: residual_ke_j = 5J, threshold = 5000J → energy_ratio clips to 0
    }

    #[test]
    fn ammo_rack_small_arms_cookoff_at_threshold() {
        // Large calibre at high residual velocity: 42.8g .50 BMG at 500 m/s →
        // 0.5 * 0.0428 * 500^2 = 5350 J → just above 5 kJ threshold
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::SmallArms,
        });
        // Use a high residual velocity to clearly exceed threshold
        let r = eval(&c, 800.0, 42.8, "ap");
        // At 0.5 * 0.0428 * 800^2 = 13,696 J >> 5000 J → cookoff likely
        assert!(
            r.component_destroyed || r.fire_started,
            "significant residual energy above small-arms threshold should cause cookoff or fire"
        );
    }

    #[test]
    fn ammo_rack_heat_sensitive_cookoff() {
        // HEAT ammo threshold is 1 kJ, sensitivity = 2.0.
        // Need cookoff_prob > 0.5 → energy_ratio > 1.347.
        // 9.5 g at 600 m/s → 0.5 * 0.0095 * 600^2 = 1710 J → ratio 1.71
        // cookoff_prob = 1 - exp(-2.0 * 0.71) = 0.760 > 0.5 ✓
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::HEAT,
        });
        let r = eval(&c, 600.0, 9.5, "ap");
        assert!(
            r.component_destroyed || r.explosion,
            "HEAT ammo should cookoff above 1 kJ threshold at 1710 J residual"
        );
    }

    #[test]
    fn ammo_rack_low_energy_no_damage() {
        // 4 g at 25 m/s → 1.25 J, far below any threshold
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::CannonShells,
        });
        let r = eval(&c, 25.0, 4.0, "ball");
        assert!(!r.explosion);
        assert!(!r.fire_started);
        assert!(!r.component_destroyed);
    }

    #[test]
    fn ammo_rack_incendiary_increases_fire_chance() {
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::SmallArms,
        });
        // 4 g at 600 m/s → 720 J — below 5 kJ threshold, but incendiary
        // rounds have higher fire multiplier (3.0)
        // fire_prob = 0.05 * 3.0 * 1.0 * 0.0 (energy_ratio < 1.0 so clamped to 0)
        // Actually below threshold so fire_prob path isn't reached.
        // Just ensuring it runs without panic.
        let r = eval(&c, 600.0, 4.0, "incendiary");
        assert!(r.residual_energy_j >= 0.0);
    }

    // ── Fuel tank tests ─────────────────────────────────────────────────────────

    #[test]
    fn fuel_tank_petrol_ignites_easier_than_diesel() {
        // Same conditions for both fuel types at moderate energy
        let c_pet = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Petrol,
        });
        let c_die = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Diesel,
        });
        // 9.5 g at 600 m/s → 1710 J → above leak threshold (200 J)
        // Both tanks are perforated → leaking → disabled.
        let r_pet = eval(&c_pet, 600.0, 9.5, "ball");
        let r_die = eval(&c_die, 600.0, 9.5, "ball");
        // Perforated fuel tank always leaks → component_disabled.
        assert!(
            r_pet.component_disabled,
            "petrol tank should leak when perforated"
        );
        assert!(
            r_die.component_disabled,
            "diesel tank should leak when perforated"
        );
        // Petrol has higher fire probability than diesel.  At deterministic
        // threshold (p > 0.5), both fire_probs are below 0.5 at this energy.
        assert!(
            !r_pet.explosion,
            "petrol vapour explosion unlikely at 1710 J"
        );
        assert!(
            !r_die.explosion,
            "diesel vapour explosion unlikely at 1710 J"
        );
    }

    #[test]
    fn fuel_tank_below_leak_threshold() {
        // 4 g at 50 m/s → 5 J < 200 J threshold
        let c = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Diesel,
        });
        let r = eval(&c, 50.0, 4.0, "ball");
        assert!(!r.explosion);
        assert!(!r.fire_started);
        assert!(!r.component_disabled);
    }

    #[test]
    fn fuel_tank_explosion_high_energy() {
        // 42.8 g .50 BMG at 800 m/s → 13,696 J → well above diesel
        // explosion threshold of 8 kJ
        let c = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Diesel,
        });
        let r = eval(&c, 800.0, 42.8, "api");
        assert!(
            r.explosion || r.fire_started,
            "high energy into fuel tank should cause explosion or fire"
        );
    }

    // ── Engine tests ────────────────────────────────────────────────────────────

    #[test]
    fn engine_low_energy_minor_damage() {
        // 4 g at 200 m/s → 80 J → very low relative to engine mass
        let c = cfg(ComponentType::Engine {
            engine_type: EngineType::Diesel,
        });
        let r = eval(&c, 200.0, 4.0, "ball");
        assert!(!r.component_destroyed);
        assert!(!r.component_disabled);
        // Mobility loss should be small (< 0.15 absorbed fraction → < 7.5%)
        assert!(r.mobility_loss_fraction < 0.10);
    }

    #[test]
    fn engine_full_kill_high_energy() {
        // Large calibre at high velocity:
        // 42.8 g at 900 m/s → 17,334 J into 800 kg diesel block
        // absorbed fraction = 17334 / (800*150) = 0.144 → minor damage?
        // Hmm, need more energy. Try 42.8g at 1500 m/s → 48,150 J
        // absorbed = 48150 / 120000 = 0.40 → disabled
        let c = cfg(ComponentType::Engine {
            engine_type: EngineType::Diesel,
        });
        let r = eval(&c, 1500.0, 42.8, "ap");
        assert!(
            r.component_disabled || r.mobility_loss_fraction > 0.3,
            "high energy into diesel engine should cause major damage"
        );
    }

    #[test]
    fn engine_petrol_lighter_block_more_damage() {
        // 9.5 g at 800 m/s → 3040 J
        // Petrol block: 200 kg, max absorb = 30,000 J
        // absorbed fraction = 3040 / 30000 = 0.101 → minor
        // Diesel block: 800 kg, max absorb = 120,000 J
        // absorbed fraction = 3040 / 120000 = 0.025 → trivial
        let c_pet = cfg(ComponentType::Engine {
            engine_type: EngineType::Petrol,
        });
        let c_die = cfg(ComponentType::Engine {
            engine_type: EngineType::Diesel,
        });
        let r_pet = eval(&c_pet, 800.0, 9.5, "ball");
        let r_die = eval(&c_die, 800.0, 9.5, "ball");
        assert!(
            r_pet.mobility_loss_fraction >= r_die.mobility_loss_fraction,
            "petrol engine (lighter) should lose more mobility than diesel (heavier)"
        );
    }

    #[test]
    fn engine_incendiary_fire() {
        // 9.5 g at 900 m/s → 3847 J
        // Petrol engine: 200 kg, absorbed fraction = 3847 / 30000 = 0.128
        // Below 0.20 fire threshold, but incendiary multiplier = 3.0
        // fire_prob = 0.05 * 0.128 * 10 * 3.0 = 0.192 → possible
        let c = cfg(ComponentType::Engine {
            engine_type: EngineType::Petrol,
        });
        let r = eval(&c, 900.0, 9.5, "incendiary");
        // Just verify it runs and gives sensible results
        assert!(r.secondary_fragments >= 0);
    }

    // ── Transmission tests ──────────────────────────────────────────────────────

    #[test]
    fn transmission_minor_damage() {
        let c = cfg(ComponentType::Transmission);
        let r = eval(&c, 200.0, 4.0, "ball");
        assert!(!r.component_destroyed);
        assert!(!r.component_disabled);
    }

    #[test]
    fn transmission_severe_damage() {
        // 42.8 g at 1500 m/s → 48,150 J; max absorb = 60,000 J;
        // absorbed fraction = 0.80 → destroyed
        let c = cfg(ComponentType::Transmission);
        let r = eval(&c, 1500.0, 42.8, "ap");
        assert!(
            r.mobility_loss_fraction > 0.5,
            "high energy into transmission should cause heavy mobility loss"
        );
    }

    // ── Crew injury tests ───────────────────────────────────────────────────────

    #[test]
    fn crew_no_spall_no_casualty() {
        // No BAD fragments → no crew casualties at low energy
        let c = cfg(ComponentType::Crew {
            protection_level: CrewProtection::None,
        });
        let r = eval(&c, 50.0, 4.0, "ball");
        assert_eq!(r.crew_casualties, 0);
    }

    #[test]
    fn crew_spall_causes_casualty() {
        // Moderate BAD load: 50 fragments, 45° spray, 50g total mass, 200 m/s
        // avg_frag_mass = 50g / 50 = 1g = 0.001 kg
        // vel_factor = (45/45).clamp(0.2, 1.0) = 1.0
        // 100.0 / 200.0.max(100.0) = 0.5 → max(1.0, 0.5) = 1.0
        // frag_vel = 200 * 1.0 = 200 m/s
        // frag_ke = 0.5 * 0.001 * 200^2 = 20 J → below 80 J threshold,
        // and below 40 J (half threshold) → 0 casualties
        let c = cfg(ComponentType::Crew {
            protection_level: CrewProtection::None,
        });
        let r = eval_bad(&c, 200.0, 9.5, "ball", 7.62, 50, 45.0, 50.0);
        assert_eq!(
            r.crew_casualties, 0,
            "low-energy BAD fragments should not cause casualties"
        );
    }

    #[test]
    fn crew_heavy_spall_causes_casualty() {
        // Heavier fragments: 600g total, 10 fragments, 800 m/s, 15° spray
        // avg_frag_mass = 60g = 0.06 kg
        // vel_factor = 15/45 = 0.333, frag_vel = 800 * 0.333 = 266.4 m/s
        // frag_ke = 0.5 * 0.06 * 266.4^2 = 2,129 J → >> 80 J
        let c = cfg(ComponentType::Crew {
            protection_level: CrewProtection::None,
        });
        let r = eval_bad(&c, 800.0, 9.5, "ball", 7.62, 10, 15.0, 600.0);
        assert!(
            r.crew_casualties >= 1,
            "heavy BAD fragments should cause crew casualties"
        );
    }

    #[test]
    fn crew_spall_liner_reduces_casualties() {
        // Same heavy BAD load with spall liner
        // Protection factor: SpallLiner = 5.0 → effective frag KE = 2129/5 = 426 J
        // Still above 80 J threshold → casualties expected
        let c_none = cfg(ComponentType::Crew {
            protection_level: CrewProtection::None,
        });
        let c_liner = cfg(ComponentType::Crew {
            protection_level: CrewProtection::SpallLiner,
        });
        let r_none = eval_bad(&c_none, 800.0, 9.5, "ball", 7.62, 10, 15.0, 600.0);
        let r_liner = eval_bad(&c_liner, 800.0, 9.5, "ball", 7.62, 10, 15.0, 600.0);
        // Spall liner should reduce casualties (fewer fragments above threshold)
        assert!(
            r_liner.crew_casualties <= r_none.crew_casualties,
            "spall liner should not increase casualties"
        );
    }

    #[test]
    fn crew_heavy_protection_no_casualties() {
        // Heavy protection (factor 10) against moderate BAD
        // 20 fragments, 30° spray, 100g total, 500 m/s
        // avg_frag_mass = 5g = 0.005 kg; vel_factor = 30/45 = 0.667
        // frag_vel = 500 * 0.667 * 0.2 = 66.7; frag_ke = 0.5 * 0.005 * 66.7^2 / 10 = 1.1 J
        // Well below 80 J → 0 casualties
        let c = cfg(ComponentType::Crew {
            protection_level: CrewProtection::Heavy,
        });
        let r = eval_bad(&c, 500.0, 9.5, "ball", 7.62, 20, 30.0, 100.0);
        assert_eq!(
            r.crew_casualties, 0,
            "heavy protection should prevent casualties"
        );
    }

    // ── Edge-case / integration tests ───────────────────────────────────────────

    #[test]
    fn zero_velocity_no_damage() {
        let types = [
            ComponentType::AmmoRack {
                ammo_type: AmmoStoredType::SmallArms,
            },
            ComponentType::FuelTank {
                fuel_type: FuelType::Diesel,
            },
            ComponentType::Engine {
                engine_type: EngineType::Diesel,
            },
            ComponentType::Transmission,
            ComponentType::Crew {
                protection_level: CrewProtection::None,
            },
        ];
        for ct in &types {
            let c = cfg(*ct);
            let r = eval(&c, 0.0, 4.0, "ball");
            assert!(!r.explosion, "{:?}: no explosion at zero velocity", ct);
            assert!(!r.fire_started, "{:?}: no fire at zero velocity", ct);
            assert!(
                !r.component_destroyed,
                "{:?}: no destruction at zero velocity",
                ct
            );
        }
    }

    #[test]
    fn residual_energy_never_negative() {
        let c = cfg(ComponentType::Engine {
            engine_type: EngineType::Diesel,
        });
        let r = eval(&c, 9999.0, 1000.0, "ap");
        assert!(
            r.residual_energy_j >= 0.0,
            "residual energy should never be negative (got {})",
            r.residual_energy_j
        );
    }

    #[test]
    fn ammo_rack_mixed_type_uses_lowest_threshold() {
        // Mixed ammo uses the lowest threshold (1 kJ, sensitivity 1.2).
        // Need cookoff_prob > 0.5 → energy_ratio > 1.578.
        // 9.5 g at 650 m/s → 0.5 * 0.0095 * 650^2 = 2007 J → ratio 2.007
        // cookoff_prob = 1 - exp(-1.2 * 1.007) = 0.702 > 0.5 ✓
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::Mixed,
        });
        let r = eval(&c, 650.0, 9.5, "ball");
        assert!(
            r.component_destroyed || r.explosion,
            "Mixed ammo rack (1 kJ threshold) should cookoff at 2007 J residual"
        );
    }

    #[test]
    fn jp8_intermediate_ignition() {
        // JP8 should be harder to ignite than petrol but easier than diesel
        let c_jp8 = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::JP8,
        });
        let c_pet = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Petrol,
        });
        let c_die = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Diesel,
        });

        // Same conditions: 9.5g at 700 m/s → 2327 J, all >> 200 J threshold
        let r_jp8 = eval(&c_jp8, 700.0, 9.5, "ball");
        let r_pet = eval(&c_pet, 700.0, 9.5, "ball");
        let r_die = eval(&c_die, 700.0, 9.5, "ball");

        // All tanks leak when perforated → component_disabled is true.
        assert!(
            r_pet.component_disabled,
            "petrol tank should leak at 2327 J"
        );
        assert!(r_jp8.component_disabled, "JP8 tank should leak at 2327 J");
        assert!(
            r_die.component_disabled,
            "diesel tank should leak at 2327 J"
        );
        // Base fire probs at 2327 J (all < 0.5):
        //   Petrol:  0.08 * 2.327 = 0.186 → no fire
        //   JP8:     0.04 * 2.327 = 0.093 → no fire
        //   Diesel:  0.02 * 2.327 = 0.047 → no fire
        assert!(
            !r_pet.fire_started,
            "petrol needs >~6250 J for fire at deterministic threshold"
        );
        assert!(!r_jp8.fire_started, "JP8 needs >~12500 J for fire");
        assert!(!r_die.fire_started, "diesel needs >~25000 J for fire");
    }
}
