// ABE - Soft Tissue / Wound Ballistics Model
//
// Models the interaction between projectiles and soft (biological) tissue.
// Implements temporary cavity, permanent wound channel, penetration depth,
// and energy deposition models used in terminal ballistics.
//
// References:
//   - Fackler, M.L., "Wound Ballistics: A Review of Common Misconceptions"
//   - FBI HPR (Handgun Wounding Effectiveness) reports, FBI Academy
//   - Nennstiel, R., "Wound Ballistics" in Encyclopedia of Forensic Sciences
//   - Peters, C.E., "Wound Ballistics of Yawed Rifle Projectiles" (AD-A233 621)
//   - Sturdivan, L.M., "Mathematical Modeling of Wound Ballistics"
//   - UK Defence Standard 13-100 (Fragment Simulating Projectiles)
//   - MacPherson, D., "Bullet Penetration: Modeling the Dynamics and
//     the Wounding Capacity of Projectiles in Soft Tissue" (1994)
//   - NIJ Standard 0101.06 (Ballistic Resistance of Body Armor)
//   - STANAG 4569 (Protection Levels for Logistic and Light Armored Vehicles)
//   - JBM Ballistics / PRODAS trajectory tables reference data
// ponytail: bone model constants are forward-looking

#![allow(dead_code)]

// ── Re-exports from submodules ────────────────────────────────────────────────
// Keep public API paths unchanged: crate::effects::soft_tissue::Type still works.
pub use crate::effects::babt::{BABTResult, evaluate_babt, nij_bfd_compliant};
pub use crate::effects::bone_penetration::{BoneImpactResult, BoneType, evaluate_bone_impact};
pub use crate::effects::hydraulic_shock::{HydraulicShockResult, evaluate_hydraulic_shock};
pub use crate::effects::nijij_reference::{
    NIJLevel, NIJThreat, STANAGLevel, STANAGThreat, nij_threat, stanag_threat,
};
pub use crate::effects::trajectory_data::{
    AmmoReference, TrajectorySample, TrajectoryValidationResult, ammo_references,
    check_trajectory_monotonic, compute_energy_at_range, interpolate_trajectory,
};

// ── Physical constants ────────────────────────────────────────────────────────

/// Tissue density in kg/m³ (nominally water-equivalent, ~5 % denser).
pub(crate) const TISSUE_DENSITY: f64 = 1040.0;

/// Drag coefficient of a typical projectile in soft tissue.
/// Caliber-dependent; 0.45–0.55 for pistol/rifle rounds in water simulant.
pub(crate) const TISSUE_CD: f64 = 0.50;

/// Temporary cavity expansion constant (m / sqrt(N)).
/// Relates energy deposition per unit path length to peak cavity diameter.
/// D_temp = 2 * k_c * sqrt(dE/dx)
/// For typical muscle/ballistic gelatin: k_c ≈ 0.0003–0.0007 m/N^0.5
/// giving temporary cavities of 30–100 mm for handgun rounds and
/// 60–200 mm (often capped by tissue rupture) for yawing rifle rounds.
/// Reference: Fackler, Peters, FBI HPR ballistic gelatin data.
pub(crate) const CAVITY_CONSTANT: f64 = 0.0005;

/// Minimum retained velocity (m/s) for wounding significance.
/// Below ∼50 m/s the projectile delivers negligible energy to tissue.
const WOUND_THRESHOLD_MS: f64 = 50.0;

// ── Wound ballistic result ─────────────────────────────────────────────────────

/// Result of a soft-tissue wound ballistics evaluation.
#[derive(Debug, Clone)]
pub struct WoundResult {
    /// Total penetration depth in soft tissue (metres).
    pub penetration_depth_m: f64,
    /// Peak temporary cavity diameter (metres). The maximum radial
    /// stretch the tissue experiences as the projectile passes through.
    pub temp_cavity_diameter_m: f64,
    /// Permanent (crushed tissue) wound channel diameter (metres).
    /// For FMJ this is ≈ projectile diameter; for expanding bullets it
    /// may be 1.5–2.5× calibre.
    pub perm_cavity_diameter_m: f64,
    /// Total kinetic energy deposited in the wound track (J).
    pub energy_deposited_j: f64,
    /// Energy deposition per unit path length at the point of peak
    /// temporary cavity (J/cm). Used to compare wounding potential
    /// between calibres.
    pub peak_edep_j_per_cm: f64,
    /// Whether the projectile yawed in tissue (rifle rounds typically
    /// yaw 90–180° within the first 10–20 cm, dramatically increasing
    /// energy deposition).
    pub yawed: bool,
    /// Penetration depth at which the projectile yawed (m). 0.0 if
    /// the projectile did not yaw (handgun rounds, or subsonic).
    pub yaw_depth_m: f64,
    /// Fragmentation contribution: additional mass from projectiles
    /// that break up in tissue (grams). M193/M855 can shed jacket
    /// fragments, significantly enlarging the wound track.
    pub frag_mass_g: f64,
    /// Whether the projectile penetrated a bone in the wound track.
    pub bone_penetrated: bool,
    /// Number of bone fragments generated by impact (0 if no bone hit).
    pub bone_fragments: i32,
    /// Energy deposited in bone during impact (J).
    pub bone_energy_j: f64,
}

// ── Main evaluation ────────────────────────────────────────────────────────────

/// Evaluate wound ballistics for a projectile entering soft tissue.
///
/// Uses a three-phase model:
/// 1. **Penetration** — the projectile decelerates in tissue as a
///    dense-fluid drag problem: `F = ½·ρ·A·Cd·v²`. Penetration depth
///    is found by integrating the drag equation.
/// 2. **Temporary cavity** — the peak radial stretch diameter at a
///    given depth scales with sqrt(dE/dx). The maximum over the wound
///    track is reported.
/// 3. **Permanent cavity** — the crushed-tissue track diameter. For
///    non-expanding projectiles this is ≈ projectile calibre. Yawing
///    and fragmentation increase it substantially.
///
/// # Arguments
/// * `velocity_ms` — Impact velocity (m/s).
/// * `mass_g` — Projectile mass (grams).
/// * `caliber_m` — Projectile diameter (metres).
/// * `projectile_type` — Projectile construction identifier
///   ("fmj", "soft_point", "hollow_point", "ball", "ap", etc.).
///
/// # Returns
/// `WoundResult` summarising the wound channel properties.
pub fn evaluate(
    velocity_ms: f64,
    mass_g: f64,
    caliber_m: f64,
    projectile_type: &str,
) -> WoundResult {
    if velocity_ms <= WOUND_THRESHOLD_MS || mass_g <= 0.0 || caliber_m <= 0.0 {
        return WoundResult {
            penetration_depth_m: 0.0,
            temp_cavity_diameter_m: 0.0,
            perm_cavity_diameter_m: 0.0,
            energy_deposited_j: 0.0,
            peak_edep_j_per_cm: 0.0,
            yawed: false,
            yaw_depth_m: 0.0,
            frag_mass_g: 0.0,
            bone_penetrated: false,
            bone_fragments: 0,
            bone_energy_j: 0.0,
        };
    }

    let mass_kg = mass_g / 1000.0;
    let area = std::f64::consts::PI * (caliber_m / 2.0).powi(2);
    let proj_type = projectile_type.to_lowercase();

    // ── 1. Penetration depth ─────────────────────────────────────────
    // Drag equation in tissue: m·dv/dt = -½·ρ·A·Cd·v²
    // Integrated: x = (2·m / (ρ·A·Cd)) · ln(v₀ / v_threshold)
    //
    // This gives the "total stopping distance" in tissue-homologous
    // material (ballistic gelatin or muscle tissue).
    let drag_factor = TISSUE_DENSITY * area * TISSUE_CD / (2.0 * mass_kg);
    let penetration_depth = if drag_factor > 0.0 {
        (velocity_ms / WOUND_THRESHOLD_MS.max(1.0)).ln() / drag_factor
    } else {
        0.0
    };
    let penetration_depth = penetration_depth.min(1.5); // sanity cap: 1.5 m is very deep

    // ── 2. Energy deposition per unit length (dE/dx) ──────────────────
    // dE/dx = F_drag = ½·ρ·A·Cd·v(x)²
    // The velocity at each point x: v(x) = v₀·exp(-drag_factor·x)
    // So dE/dx(x) = ½·ρ·A·Cd·v₀²·exp(-2·drag_factor·x)
    //
    // Peak dE/dx is at the surface (x=0) for non-yawing projectiles.
    // For yawing rifles, the actual peak occurs post-yaw.
    let edep_surface = 0.5 * TISSUE_DENSITY * area * TISSUE_CD * velocity_ms.powi(2);

    // ── 3. Yaw depth (rifle rounds) ───────────────────────────────────
    // Rifle-calibre projectiles (v₀ > ~650 m/s, L/D > 2.5) typically
    // yaw 90–180° within the first 10–20 cm of penetration. The yaw
    // dramatically increases presented area, hence energy deposition.
    //
    // Yaw onset depth is empirically ~8–15 calibres for FMJ rifle rounds:
    //   yaw_depth = k_yaw * caliber_m, where k_yaw ≈ 8–15
    //
    // Aspect ratio estimate: L/D = mass_kg / (ρ · A · D) where
    //   ρ ≈ 8500 kg/m³ (generic lead-alloy projectile density).
    let is_ap = proj_type == "ap" || proj_type == "armor_piercing";
    let density_est = 8500.0; // kg/m³ — generic projectile material
    let length_m = mass_kg / (density_est * area).max(1e-30);
    let aspect_ratio = length_m / caliber_m.max(1e-30);
    let is_rifle = velocity_ms > 650.0 && aspect_ratio > 2.5;
    let (yawed, yaw_depth_m, yaw_area_multiplier) = if is_rifle && !is_ap {
        // Yaw depth: 8–15 calibres; longer/heavier projectiles yaw later
        let k_yaw = 8.0 + 4.0 * (aspect_ratio / 5.0).clamp(0.0, 1.0);
        let yaw_d = (k_yaw * caliber_m).min(penetration_depth * 0.5);
        // Post-yaw presented area increases 3–6× (side-on vs nose-on)
        let area_mult = 4.0;
        (yaw_d > 0.01, yaw_d, area_mult)
    } else {
        (false, 0.0, 1.0)
    };

    // ── 4. Fragmentation in tissue ────────────────────────────────────
    // High-velocity projectiles (v > ~700 m/s) can fragment in tissue,
    // especially varmint/soft-point designs. The jacket may shed at the
    // yaw point, creating 2–20 secondary fragments.
    let (frag_mass_g, frag_area_mult) = if yawed && velocity_ms > 700.0 {
        let proj_frac = match proj_type.as_str() {
            "soft_point" | "hollow_point" => 0.05, // 5 % mass shed
            "fmj" | "ball" => 0.02,                // 2 % for military ball
            "varmint" | "sp" => 0.08,              // 8 % for rapid-expanding
            _ => 0.01,
        };
        if velocity_ms > 900.0 {
            // M193/M855 regime: jacket separation
            (mass_g * proj_frac, 1.5)
        } else {
            (mass_g * proj_frac * 0.5, 1.2)
        }
    } else {
        (0.0, 1.0)
    };

    // ── 5. Temporary cavity diameter ──────────────────────────────────
    // Peak cavity diameter scales with sqrt(dE/dx) at the point of
    // maximum energy deposition. For yawing projectiles this is the
    // post-yaw phase; for non-yawing it is the surface value.
    //
    // D_temp = 2 * k_c * sqrt(dE/dx)
    // where k_c = CAVITY_CONSTANT. The factor of 2 converts radial
    // expansion to full diameter.
    let edep_max = if yawed {
        // Apply yaw area multiplier + fragmentation
        edep_surface * yaw_area_multiplier * frag_area_mult
    } else {
        edep_surface
    };
    let temp_cavity = 2.0 * CAVITY_CONSTANT * edep_max.sqrt();
    // Cap temporary cavity at 15× calibre (tissue rupture limit)
    let temp_cavity = temp_cavity.min(15.0 * caliber_m);

    // ── 6. Permanent cavity diameter ──────────────────────────────────
    // The crushed tissue track. Non-expanding: ≈0.9× calibre.
    // Expanding/yawing: up to 2.5× calibre.
    let perm_diameter = match proj_type.as_str() {
        "soft_point" | "hollow_point" => {
            if velocity_ms > 700.0 {
                // Full expansion
                (2.0 * caliber_m).min(3.0 * caliber_m)
            } else {
                // Partial expansion
                (1.4 * caliber_m).min(2.0 * caliber_m)
            }
        },
        "fmj" | "ball" => {
            if yawed {
                // Yawed FMJ creates a larger permanent cavity post-yaw
                0.9 * caliber_m + 0.5 * caliber_m * yaw_area_multiplier
            } else {
                0.9 * caliber_m // Minimal permanent cavity
            }
        },
        "varmint" | "sp" => {
            if velocity_ms > 800.0 {
                2.2 * caliber_m
            } else {
                1.5 * caliber_m
            }
        },
        "ap" | "armor_piercing" => 0.8 * caliber_m, // AP penetrates with minimal expansion
        _ => 0.9 * caliber_m,
    };
    let perm_cavity = perm_diameter.min(4.0 * caliber_m);

    // ── 7. Total energy deposited ─────────────────────────────────────
    // Integrate dE/dx over the penetration depth. For the simplified
    // model: E_deposited = ½·m·(v₀² - v_threshold²)
    // Actual losses to yaw and fragmentation increase deposition.
    let ke_initial = 0.5 * mass_kg * velocity_ms.powi(2);
    let ke_retained = 0.5 * mass_kg * WOUND_THRESHOLD_MS.powi(2);
    let mut edep = (ke_initial - ke_retained).max(0.0);

    // Yaw/fragmentation increase the effective drag, so more energy
    // is deposited in a shorter distance. Apply a multiplier.
    let edep_mult = if yawed { 1.3 } else { 1.0 } * (1.0 + frag_mass_g / mass_g * 2.0);
    edep *= edep_mult;

    // ── 8. Peak energy deposition per cm ──────────────────────────────
    let peak_edep_j_per_cm = edep_max * 0.01; // Convert J/m → J/cm

    WoundResult {
        penetration_depth_m: penetration_depth,
        temp_cavity_diameter_m: temp_cavity,
        perm_cavity_diameter_m: perm_cavity,
        energy_deposited_j: edep,
        peak_edep_j_per_cm,
        yawed,
        yaw_depth_m,
        frag_mass_g,
        bone_penetrated: false,
        bone_fragments: 0,
        bone_energy_j: 0.0,
    }
}

/// Evaluate wound ballistics with optional bone interaction.
///
/// Extends `evaluate()` with a bone interaction model. If `bone` is `Some`,
/// the projectile first penetrates soft tissue to reach the bone (assumed
/// at `bone_depth_m`), then the bone impact is evaluated, and soft tissue
/// penetration continues with the post-bone velocity.
///
/// # Arguments
/// * `velocity_ms` — Impact velocity (m/s).
/// * `mass_g` — Projectile mass (grams).
/// * `caliber_m` — Projectile diameter (metres).
/// * `projectile_type` — Projectile construction identifier.
/// * `bone` — Optional tuple of (BoneType, impact_angle_deg, bone_depth_m).
///
/// # Returns
/// `WoundResult` with bone interaction effects included.
pub fn evaluate_extended(
    velocity_ms: f64,
    mass_g: f64,
    caliber_m: f64,
    projectile_type: &str,
    bone: Option<(BoneType, f64, f64)>,
) -> WoundResult {
    if velocity_ms <= WOUND_THRESHOLD_MS || mass_g <= 0.0 || caliber_m <= 0.0 {
        return WoundResult {
            penetration_depth_m: 0.0,
            temp_cavity_diameter_m: 0.0,
            perm_cavity_diameter_m: 0.0,
            energy_deposited_j: 0.0,
            peak_edep_j_per_cm: 0.0,
            yawed: false,
            yaw_depth_m: 0.0,
            frag_mass_g: 0.0,
            bone_penetrated: false,
            bone_fragments: 0,
            bone_energy_j: 0.0,
        };
    }

    let (bone_type, impact_angle_deg, bone_depth_m) = match bone {
        Some(b) => b,
        None => {
            // No bone: delegate to standard evaluate
            return evaluate(velocity_ms, mass_g, caliber_m, projectile_type);
        },
    };

    let mass_kg = mass_g / 1000.0;
    let area = std::f64::consts::PI * (caliber_m / 2.0).powi(2);
    let proj_type = projectile_type.to_lowercase();

    // ── 1. Compute pre-bone soft tissue penetration ─────────────────────
    // Drag equation gives us the velocity at depth bone_depth_m
    let drag_factor = TISSUE_DENSITY * area * TISSUE_CD / (2.0 * mass_kg);
    let vel_at_bone = if drag_factor > 0.0 {
        velocity_ms * (-drag_factor * bone_depth_m).exp()
    } else {
        velocity_ms
    };

    // If velocity at bone is below threshold, just do standard eval
    if vel_at_bone <= WOUND_THRESHOLD_MS {
        return evaluate(velocity_ms, mass_g, caliber_m, projectile_type);
    }

    // ── 2. Evaluate bone impact ─────────────────────────────────────────
    let bone_result = evaluate_bone_impact(
        vel_at_bone,
        mass_g,
        caliber_m,
        projectile_type,
        bone_type,
        impact_angle_deg,
    );

    // ── 3. Continue soft tissue penetration after bone ──────────────────
    let (total_penetration, temp_cavity, perm_cavity, edep, peak_edep, yawed, yaw_d, frag) =
        if bone_result.penetrated {
            // Post-bone: continue with reduced velocity
            let post_bone_vel = bone_result.velocity_after_bone_ms;
            let _post_bone_ke = 0.5 * mass_kg * post_bone_vel.powi(2);

            // Remaining penetration depth after bone
            let post_bone_pen = if drag_factor > 0.0 && post_bone_vel > WOUND_THRESHOLD_MS {
                (post_bone_vel / WOUND_THRESHOLD_MS.max(1.0)).ln() / drag_factor
            } else {
                0.0
            };
            let total_pen = bone_depth_m + post_bone_pen.min(1.5);

            // Yaw: bone impact can induce yaw even in handgun rounds
            let is_ap = proj_type == "ap" || proj_type == "armor_piercing";
            let density_est = 8500.0;
            let length_m = mass_kg / (density_est * area).max(1e-30);
            let aspect_ratio = length_m / caliber_m.max(1e-30);
            let is_rifle = post_bone_vel > 650.0 && aspect_ratio > 2.5;
            let yawed = bone_result.deflection_angle_deg > 10.0 || (is_rifle && !is_ap);
            let yaw_d = if yawed { bone_depth_m } else { 0.0 };

            // Post-bone yaw area multiplier
            let yaw_area_mult = if yawed { 4.0 } else { 1.0 };

            // dE/dx at bone location
            let edep_bone = 0.5 * TISSUE_DENSITY * area * TISSUE_CD * post_bone_vel.powi(2);

            // Pre-bone dE/dx at surface (highest pre-bone velocity)
            let edep_surface_pre = 0.5 * TISSUE_DENSITY * area * TISSUE_CD * velocity_ms.powi(2);

            // Bone interface energy deposition rate:
            // energy deposited in bone concentrated over ~2× bone thickness
            let bone_edep_rate =
                bone_result.energy_deposited_in_bone_j / (bone_type.thickness_m() * 2.0).max(0.001);

            // Peak dE/dx: max of pre-bone surface, bone interface, post-bone (with yaw)
            let edep_max = edep_surface_pre
                .max(bone_edep_rate)
                .max(edep_bone * yaw_area_mult);

            // Temp cavity: bone impact amplifies (1.5-2.0× near bone)
            let bone_amp = if bone_result.penetrated { 1.5 } else { 1.0 };
            let temp_cav = 2.0 * CAVITY_CONSTANT * edep_max.sqrt() * bone_amp;
            let temp_cav = temp_cav.min(15.0 * caliber_m);

            // Permanent cavity
            let perm_d = match proj_type.as_str() {
                "soft_point" | "hollow_point" => {
                    if post_bone_vel > 700.0 {
                        2.0 * caliber_m
                    } else {
                        1.4 * caliber_m
                    }
                },
                "fmj" | "ball" => {
                    if yawed {
                        0.9 * caliber_m + 0.5 * caliber_m * yaw_area_mult
                    } else {
                        0.9 * caliber_m
                    }
                },
                "varmint" | "sp" => {
                    if post_bone_vel > 800.0 {
                        2.2 * caliber_m
                    } else {
                        1.5 * caliber_m
                    }
                },
                _ => 0.9 * caliber_m,
            };
            let perm_cav = perm_d.min(4.0 * caliber_m);

            // Fragmentation: bone produces secondary fragments
            let frag_mass = bone_result.bone_fragment_mass_g * 0.5; // ~50% of bone frag mass adds to wound

            // Total energy deposited: pre-bone KE loss + bone + post-bone
            let ke_initial = 0.5 * mass_kg * velocity_ms.powi(2);
            let ke_final = 0.5 * mass_kg * WOUND_THRESHOLD_MS.powi(2);
            let total_edep = (ke_initial - ke_final).max(0.0);

            let peak_edep_j_per_cm = edep_max * 0.01;

            (
                total_pen,
                temp_cav,
                perm_cav,
                total_edep,
                peak_edep_j_per_cm,
                yawed,
                yaw_d,
                frag_mass,
            )
        } else {
            // Bone stopped projectile: penetration capped at bone depth
            let _ke_at_bone = 0.5 * mass_kg * vel_at_bone.powi(2);
            let edep = bone_result.energy_deposited_in_bone_j;

            // Cavity from energy deposited at bone
            let edep_rate = if bone_depth_m > 0.0 {
                edep / (bone_depth_m * 100.0) // J/cm
            } else {
                0.0
            };
            let temp_cav = 2.0 * CAVITY_CONSTANT * (edep / bone_depth_m.max(0.001)).sqrt();
            let temp_cav = temp_cav.min(15.0 * caliber_m);

            (
                bone_depth_m, // penetration capped
                temp_cav,
                0.9 * caliber_m, // minimal perm cavity
                edep,
                edep_rate,
                false, // no yaw (stopped)
                0.0,
                0.0,
            )
        };

    WoundResult {
        penetration_depth_m: total_penetration,
        temp_cavity_diameter_m: temp_cavity,
        perm_cavity_diameter_m: perm_cavity,
        energy_deposited_j: edep,
        peak_edep_j_per_cm: peak_edep,
        yawed,
        yaw_depth_m: yaw_d,
        frag_mass_g: frag,
        bone_penetrated: bone_result.penetrated,
        bone_fragments: bone_result.bone_fragments,
        bone_energy_j: bone_result.energy_deposited_in_bone_j,
    }
}

/// Evaluate wound profile along a discretised wound track.
///
/// Returns a vector of (depth_m, temp_cavity_diameter_m, dE_dx_J_per_m) samples
/// at `num_samples` evenly spaced points along the penetration path.
/// Useful for visualising the wound profile.
pub fn wound_profile(
    velocity_ms: f64,
    mass_g: f64,
    caliber_m: f64,
    projectile_type: &str,
    num_samples: usize,
) -> Vec<(f64, f64, f64)> {
    let result = evaluate(velocity_ms, mass_g, caliber_m, projectile_type);
    if result.penetration_depth_m <= 0.0 || num_samples == 0 {
        return Vec::new();
    }

    let mass_kg = mass_g / 1000.0;
    let area = std::f64::consts::PI * (caliber_m / 2.0).powi(2);
    let drag_factor = TISSUE_DENSITY * area * TISSUE_CD / (2.0 * mass_kg);
    let proj_type = projectile_type.to_lowercase();
    let is_ap = proj_type == "ap" || proj_type == "armor_piercing";
    let density_est = 8500.0;
    let length_m = mass_kg / (density_est * area).max(1e-30);
    let aspect_ratio = length_m / caliber_m.max(1e-30);
    let is_rifle = velocity_ms > 650.0 && aspect_ratio > 2.5;
    let yaw_depth = if is_rifle && !is_ap {
        let k_yaw = 8.0 + 4.0 * (aspect_ratio / 5.0).clamp(0.0, 1.0);
        (k_yaw * caliber_m).min(result.penetration_depth_m * 0.5)
    } else {
        f64::INFINITY
    };
    let area_base = area;
    let area_post_yaw = area_base * 4.0;
    let frag_mass = result.frag_mass_g;

    let mut profile = Vec::with_capacity(num_samples);
    for i in 0..num_samples {
        let frac = (i as f64 + 0.5) / num_samples as f64;
        let depth = result.penetration_depth_m * frac;

        // Determine effective presented area at this depth
        let effective_area = if depth >= yaw_depth {
            area_post_yaw + frag_mass / (mass_g * depth + 0.001) * area_base
        } else {
            area_base
        };

        // v(x) = v₀ · exp(-drag_factor · x)
        let v_at_depth = velocity_ms * (-drag_factor * depth).exp();
        let d_e_dx = 0.5 * TISSUE_DENSITY * effective_area * TISSUE_CD * v_at_depth.powi(2);

        // Temporary cavity at this depth
        let temp_d = 2.0 * CAVITY_CONSTANT * d_e_dx.sqrt();
        let temp_d = temp_d.min(15.0 * caliber_m);

        profile.push((depth, temp_d, d_e_dx));
    }
    profile
}

// ── ACE3 Medical Wound Classification ─────────────────────────────────────────

/// ACE3 medical wound classification type.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ACE3WoundType {
    /// Massive tissue damage from high-energy cavity.
    AvulsionWound,
    /// Standard projectile wound.
    BulletWound,
    /// Wound from bone or secondary fragments.
    ShrapnelWound,
    /// Blunt trauma from non-penetrating impact.
    ContusionWound,
    /// Crush injury (e.g. rib fracture from BABT).
    CrushWound,
}

/// ACE3 medical wound result — structured data for ACE3 medical system.
#[derive(Debug, Clone)]
pub struct ACE3MedicalResult {
    /// ACE3 wound type classification.
    pub wound_type: ACE3WoundType,
    /// Wound size (1-14, ACE3 scale).
    pub wound_size: i32,
    /// Base blood loss rate (ml/s).
    pub blood_loss_ml_per_s: f64,
    /// Pain level (1-10).
    pub pain_level: i32,
    /// Whether immediate incapacitation is likely.
    pub immediate_incapacitation: bool,
    /// Minutes until consciousness lost from blood loss (if applicable).
    pub consciousness_time_s: f64,
    /// Recommended ACE3 medical treatment.
    pub recommended_treatment: &'static str,
    /// Whether a tourniquet is applicable.
    pub tourniquet_applicable: bool,
}

/// Classify an ABE wound result for the ACE3 medical system.
///
/// Maps from wound ballistics output to ACE3 wound parameters.
///
/// # Arguments
/// * `wound_result` — Result from `evaluate()` or `evaluate_extended()`.
/// * `velocity_ms` — Impact velocity (m/s).
/// * `mass_g` — Projectile mass (g).
/// * `projectile_type` — Projectile construction identifier.
/// * `body_region` — "head", "thorax", "abdomen", "limb".
/// * `armor_penetrated` — Whether armour was penetrated.
/// * `armor_type` — Optional armour type if armour was present.
pub fn classify_ace3_wound(
    wound_result: &WoundResult,
    velocity_ms: f64,
    mass_g: f64,
    projectile_type: &str,
    body_region: &str,
    armor_penetrated: bool,
    _armor_type: Option<&str>,
) -> ACE3MedicalResult {
    let mass_kg = mass_g / 1000.0;
    let _proj_lower = projectile_type.to_lowercase();
    let region = body_region.to_lowercase();

    // ── Compute energy deposition per cm ───────────────────────────────
    let edep_j_per_cm = wound_result.peak_edep_j_per_cm;

    // ── Determine wound type ───────────────────────────────────────────
    let wound_type = if wound_result.yawed && wound_result.frag_mass_g > 0.0 && edep_j_per_cm > 30.0
    {
        // Yawed + fragmented = avulsion
        ACE3WoundType::AvulsionWound
    } else if wound_result.temp_cavity_diameter_m > 0.10 && edep_j_per_cm > 40.0 {
        // Large temporary cavity + high energy deposition
        ACE3WoundType::AvulsionWound
    } else if wound_result.yawed {
        // Yawed but no fragmentation
        ACE3WoundType::BulletWound
    } else if wound_result.bone_fragments > 0 && wound_result.bone_penetrated {
        // Bone generates secondary fragments
        ACE3WoundType::ShrapnelWound
    } else if !armor_penetrated {
        // Non-penetrating
        // Approximate BABT from KE — armor usually transmits 3-8%
        let approx_babt = 0.5 * mass_kg * velocity_ms.powi(2) * 0.05; // ~5% transmitted
        if approx_babt > 50.0 {
            ACE3WoundType::CrushWound
        } else {
            ACE3WoundType::ContusionWound
        }
    } else {
        ACE3WoundType::BulletWound
    };

    // ── Wound size mapping ─────────────────────────────────────────────
    // Caliber-based base size
    let caliber_mm = if wound_result.perm_cavity_diameter_m > 0.0 {
        wound_result.perm_cavity_diameter_m * 1000.0
    } else {
        5.56 // default
    };

    let base_size = if caliber_mm < 5.0 {
        // < 5mm: size 1-3
        1 + (caliber_mm / 2.0) as i32
    } else if caliber_mm < 8.0 {
        // 5-8mm: size 3-6
        3 + ((caliber_mm - 5.0) / 1.5) as i32
    } else if caliber_mm < 12.0 {
        // 8-12mm: size 5-9
        5 + ((caliber_mm - 8.0) / 1.0) as i32
    } else {
        // > 12mm: size 8-14
        8 + ((caliber_mm - 12.0) / 0.8) as i32
    };
    let mut wound_size = base_size.clamp(1, 14);

    // Yaw/frag add 2-5 to size
    if wound_result.yawed {
        wound_size += 2;
    }
    if wound_result.frag_mass_g > 0.5 {
        wound_size += 3;
    } else if wound_result.frag_mass_g > 0.0 {
        wound_size += 1;
    }

    // Body region: head wounds smaller but more severe
    if region.as_str() == "head" {
        wound_size = wound_size.clamp(1, 8);
    }
    let wound_size = wound_size.clamp(1, 14);

    // ── Blood loss rate ────────────────────────────────────────────────
    let caliber_effective = if wound_result.perm_cavity_diameter_m > 0.001 {
        wound_result.perm_cavity_diameter_m
    } else {
        caliber_mm / 1000.0
    };
    let base_blood_loss = if caliber_effective < 0.006 {
        0.8 + caliber_effective * 200.0
    } else if caliber_effective < 0.010 {
        2.0 + (caliber_effective - 0.006) * 750.0
    } else {
        5.0 + (caliber_effective - 0.010) * 1500.0
    };
    let mut blood_loss = base_blood_loss.clamp(0.3, 20.0);

    // Modifiers
    if wound_result.yawed {
        blood_loss *= 2.5;
    }
    if wound_result.frag_mass_g > 0.0 {
        blood_loss *= 1.5;
    }

    // Avulsion: 10-30 ml/s
    if matches!(wound_type, ACE3WoundType::AvulsionWound) {
        blood_loss = blood_loss.clamp(10.0, 30.0);
    }

    // Head: minimal blood loss but high incapacitation
    if region == "head" {
        blood_loss = blood_loss.min(3.0);
    }

    // ── Pain level ─────────────────────────────────────────────────────
    let pain_from_size = wound_size as f64 * 0.7;
    let pain_from_edep = (edep_j_per_cm / 10.0).min(5.0);
    let mut pain_level = (pain_from_size + pain_from_edep).round() as i32;
    pain_level = pain_level.clamp(1, 10);

    match region.as_str() {
        "head" => pain_level = pain_level.max(7),
        "thorax" => pain_level = pain_level.max(4),
        "abdomen" => pain_level = pain_level.max(3),
        _ => {},
    }

    // ── Incapacitation / consciousness ─────────────────────────────────
    let immediate_incapacitation = match region.as_str() {
        "head" => true,
        "thorax" => edep_j_per_cm > 50.0,
        _ => false,
    };

    let consciousness_time_s = if blood_loss > 30.0 {
        30.0
    } else if blood_loss > 15.0 {
        60.0
    } else if blood_loss > 8.0 {
        120.0
    } else {
        300.0
    };

    // ── Treatment recommendations ──────────────────────────────────────
    let (recommended_treatment, tourniquet_applicable) = match wound_type {
        ACE3WoundType::AvulsionWound => ("surgery", false),
        ACE3WoundType::BulletWound => {
            if region == "limb" {
                ("packing", true)
            } else {
                ("packing", false)
            }
        },
        ACE3WoundType::ShrapnelWound => ("surgery", false),
        ACE3WoundType::ContusionWound => ("bandage", false),
        ACE3WoundType::CrushWound => ("surgery", false),
    };

    ACE3MedicalResult {
        wound_type,
        wound_size,
        blood_loss_ml_per_s: blood_loss,
        pain_level,
        immediate_incapacitation,
        consciousness_time_s,
        recommended_treatment,
        tourniquet_applicable,
    }
}

// ── Multi-Projectile / Shotgun Support ────────────────────────────────────────

/// Configuration for multi-projectile loads (shotgun, duplex, flechette).
pub struct MultiProjectileConfig {
    /// Number of pellets/projectiles.
    pub pellet_count: i32,
    /// Mass per pellet (g).
    pub pellet_mass_g: f64,
    /// Pellet diameter (mm).
    pub pellet_diameter_mm: f64,
    /// Muzzle velocity (m/s).
    pub muzzle_velocity_ms: f64,
    /// Total spread in MOA (minutes of angle).
    pub spread_moa: f64,
    /// Projectile type identifier.
    pub projectile_type: &'static str,
}

/// Predefined multi-projectile configs for common ammunition types.
pub fn shotgun_config(ammo_type: &str) -> MultiProjectileConfig {
    match ammo_type.to_lowercase().as_str() {
        "12ga_buckshot_00" | "00_buckshot" | "12ga_00" => MultiProjectileConfig {
            pellet_count: 8,
            pellet_mass_g: 3.5,
            pellet_diameter_mm: 9.1,
            muzzle_velocity_ms: 400.0,
            spread_moa: 30.0,
            projectile_type: "shot",
        },
        "12ga_buckshot_4" | "buckshot_4" | "12ga_4" => MultiProjectileConfig {
            pellet_count: 27,
            pellet_mass_g: 1.5,
            pellet_diameter_mm: 6.7,
            muzzle_velocity_ms: 400.0,
            spread_moa: 30.0,
            projectile_type: "shot",
        },
        "12ga_birdshot_7.5" | "birdshot_7.5" | "12ga_7.5" => MultiProjectileConfig {
            pellet_count: 350,
            pellet_mass_g: 0.13,
            pellet_diameter_mm: 2.4,
            muzzle_velocity_ms: 400.0,
            spread_moa: 40.0,
            projectile_type: "shot",
        },
        "20ga_buckshot_3" | "20ga_3" => MultiProjectileConfig {
            pellet_count: 20,
            pellet_mass_g: 1.1,
            pellet_diameter_mm: 6.1,
            muzzle_velocity_ms: 380.0,
            spread_moa: 35.0,
            projectile_type: "shot",
        },
        "duplex_556" | "duplex" => MultiProjectileConfig {
            pellet_count: 2,
            pellet_mass_g: 2.0,
            pellet_diameter_mm: 5.56,
            muzzle_velocity_ms: 900.0,
            spread_moa: 4.0,
            projectile_type: "duplex",
        },
        "flechette_12ga" | "flechette" => MultiProjectileConfig {
            pellet_count: 20,
            pellet_mass_g: 0.7,
            pellet_diameter_mm: 1.5,
            muzzle_velocity_ms: 500.0,
            spread_moa: 20.0,
            projectile_type: "flechette",
        },
        _ => MultiProjectileConfig {
            pellet_count: 8,
            pellet_mass_g: 3.5,
            pellet_diameter_mm: 9.1,
            muzzle_velocity_ms: 400.0,
            spread_moa: 30.0,
            projectile_type: "shot",
        }, // default to 00 buck
    }
}

/// Result of evaluating a multi-projectile impact against soft tissue.
pub struct MultiImpactResult {
    /// Per-pellet wound results.
    pub pellet_wounds: Vec<WoundResult>,
    /// Total penetration depth across all wound tracks (max cm).
    pub total_penetration_cm: f64,
    /// Number of pellets that actually hit the target.
    pub hits: i32,
    /// Combined kinetic energy of all hitting pellets (J).
    pub combined_energy_j: f64,
    /// Estimated effective wound volume (cc).
    pub effective_wound_volume_cc: f64,
}

/// Evaluate the impact of a multi-projectile pattern against soft tissue.
///
/// # Arguments
/// * `config` — The multi-projectile configuration.
/// * `range_m` — Range at impact (for spread calculation).
/// * `target_area_cm2` — Presented target area (cm²).
/// * `target_diameter_m` — Target diameter (m), for spread calculation.
pub fn evaluate_multi_impact(
    config: &MultiProjectileConfig,
    range_m: f64,
    target_area_cm2: f64,
    _target_diameter_m: f64,
) -> MultiImpactResult {
    if config.pellet_count <= 0 || config.pellet_mass_g <= 0.0 || range_m < 0.0 {
        return MultiImpactResult {
            pellet_wounds: Vec::new(),
            total_penetration_cm: 0.0,
            hits: 0,
            combined_energy_j: 0.0,
            effective_wound_volume_cc: 0.0,
        };
    }

    // ── Pattern spread calculation ────────────────────────────────────
    let spread_rad = (config.spread_moa / 60.0).to_radians();
    let pattern_diameter_m = range_m * spread_rad.tan();
    let pattern_radius_m = pattern_diameter_m / 2.0;
    let pattern_area_m2 = std::f64::consts::PI * pattern_radius_m.powi(2);

    // ── Hits calculation ──────────────────────────────────────────────
    let target_area_m2 = target_area_cm2 / 10000.0;
    let hit_fraction = if pattern_area_m2 > 0.0 {
        (target_area_m2 / pattern_area_m2).min(1.0)
    } else {
        1.0
    };
    let hits = ((config.pellet_count as f64) * hit_fraction).round() as i32;
    let hits = hits.min(config.pellet_count).max(0);

    // ── Per-pellet wound evaluation ────────────────────────────────────
    let pellet_caliber_m = config.pellet_diameter_mm / 1000.0;
    let mut pellet_wounds = Vec::with_capacity(hits as usize);
    let mut total_penetration_cm: f64 = 0.0;
    let mut combined_energy_j: f64 = 0.0;
    let mut effective_wound_volume_cc = 0.0;

    // Velocity at range (simplified: drag reduces velocity)
    let vel_at_range = if range_m < 10.0 {
        config.muzzle_velocity_ms * (1.0 - range_m * 0.005)
    } else if range_m < 50.0 {
        config.muzzle_velocity_ms * (1.0 - 0.05 - (range_m - 10.0) * 0.004)
    } else {
        config.muzzle_velocity_ms * (1.0 - 0.25 - (range_m - 50.0) * 0.002).max(100.0)
    };
    let vel_at_range = vel_at_range.max(50.0);

    for _ in 0..hits {
        let wound = evaluate(
            vel_at_range,
            config.pellet_mass_g,
            pellet_caliber_m,
            config.projectile_type,
        );
        let pellet_ke = 0.5 * (config.pellet_mass_g / 1000.0) * vel_at_range.powi(2);

        combined_energy_j += pellet_ke;
        total_penetration_cm = total_penetration_cm.max(wound.penetration_depth_m * 100.0);

        let cavity_radius = wound.perm_cavity_diameter_m / 2.0;
        let vol_per_pellet_cc =
            std::f64::consts::PI * cavity_radius.powi(2) * wound.penetration_depth_m * 1e6;
        effective_wound_volume_cc += vol_per_pellet_cc;

        pellet_wounds.push(wound);
    }

    let packing_factor = if hits <= 3 {
        1.0
    } else if hits <= 10 {
        0.7
    } else if hits <= 50 {
        0.5
    } else {
        0.3
    };
    effective_wound_volume_cc *= packing_factor;

    MultiImpactResult {
        pellet_wounds,
        total_penetration_cm,
        hits,
        combined_energy_j,
        effective_wound_volume_cc,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Handgun rounds ───────────────────────────────────────────────────

    #[test]
    fn fmj_9mm_penetration_in_tissue() {
        let r = evaluate(360.0, 8.0, 0.00901, "fmj");
        assert!(
            r.penetration_depth_m > 0.3 && r.penetration_depth_m < 1.0,
            "9mm FMJ should penetrate ~40-70 cm in tissue: {:.3} m",
            r.penetration_depth_m
        );
        assert!(
            r.perm_cavity_diameter_m > 0.0,
            "Permanent cavity should be positive"
        );
        assert!(
            r.temp_cavity_diameter_m > 0.0,
            "Temporary cavity should be positive"
        );
        assert!(!r.yawed, "9mm FMJ should not yaw in tissue (handgun)");
        assert!(
            r.energy_deposited_j > 100.0,
            "9mm should deposit > 100 J: {:.1} J",
            r.energy_deposited_j
        );
    }

    #[test]
    fn nine_mm_vs_44_magnum_cavity() {
        let nine = evaluate(360.0, 8.0, 0.00901, "fmj");
        let magnum = evaluate(450.0, 15.6, 0.0109, "soft_point");
        assert!(
            magnum.temp_cavity_diameter_m > nine.temp_cavity_diameter_m,
            ".44 Mag cavity ({:.4} m) should exceed 9mm ({:.4} m)",
            magnum.temp_cavity_diameter_m,
            nine.temp_cavity_diameter_m
        );
        assert!(
            magnum.energy_deposited_j > nine.energy_deposited_j,
            ".44 Mag deposits more energy"
        );
    }

    // ── Rifle rounds ────────────────────────────────────────────────────

    #[test]
    fn rifle_yaws_in_tissue() {
        let r = evaluate(930.0, 4.0, 0.00556, "fmj");
        assert!(r.yawed, "5.56mm FMJ should yaw in soft tissue");
        assert!(
            r.yaw_depth_m > 0.0,
            "Yaw depth should be positive: {:.3} m",
            r.yaw_depth_m
        );
        assert!(
            r.temp_cavity_diameter_m > 0.01,
            "Rifle round should produce large temporary cavity: {:.4} m",
            r.temp_cavity_diameter_m
        );
    }

    #[test]
    fn rifle_vs_handgun_cavity() {
        let rifle = evaluate(930.0, 4.0, 0.00556, "fmj");
        let handgun = evaluate(360.0, 8.0, 0.00901, "fmj");
        assert!(
            rifle.temp_cavity_diameter_m > handgun.temp_cavity_diameter_m,
            "Rifle temporary cavity ({:.4} m) >> handgun ({:.4} m)",
            rifle.temp_cavity_diameter_m,
            handgun.temp_cavity_diameter_m
        );
        assert!(
            rifle.energy_deposited_j > handgun.energy_deposited_j * 2.0,
            "Rifle deposits much more energy"
        );
    }

    #[test]
    fn subsonic_no_yaw() {
        let r = evaluate(310.0, 12.5, 0.00762, "fmj");
        assert!(!r.yawed, "Subsonic should not yaw in tissue");
        assert!(
            r.penetration_depth_m > 0.3,
            "300 BLK subsonic should penetrate deeply: {:.3} m",
            r.penetration_depth_m
        );
    }

    #[test]
    fn ap_projectiles_minimal_yaw() {
        let r = evaluate(880.0, 10.0, 0.00762, "ap");
        assert!(!r.yawed, "AP projectiles should resist yawing");
        assert!(
            r.frag_mass_g.abs() < 0.01,
            "AP should not fragment in tissue: {:.4} g",
            r.frag_mass_g
        );
    }

    // ── Soft point / expanding rounds ───────────────────────────────────

    #[test]
    fn soft_point_expands_in_tissue() {
        let r = evaluate(380.0, 10.0, 0.00901, "soft_point");
        assert!(
            r.perm_cavity_diameter_m > 0.012,
            "Soft point should expand: perm cavity = {:.4} m",
            r.perm_cavity_diameter_m
        );
        let fmj = evaluate(380.0, 10.0, 0.00901, "fmj");
        assert!(
            r.perm_cavity_diameter_m > fmj.perm_cavity_diameter_m,
            "Soft point perm cavity ({:.4} m) should exceed FMJ ({:.4} m)",
            r.perm_cavity_diameter_m,
            fmj.perm_cavity_diameter_m
        );
        assert!(
            r.energy_deposited_j >= fmj.energy_deposited_j,
            "Expanding bullet should deposit >= FMJ energy"
        );
    }

    // ── Edge cases ──────────────────────────────────────────────────────

    #[test]
    fn zero_velocity_no_wound() {
        let r = evaluate(0.0, 8.0, 0.00901, "fmj");
        assert_eq!(r.penetration_depth_m, 0.0);
        assert_eq!(r.temp_cavity_diameter_m, 0.0);
        assert_eq!(r.energy_deposited_j, 0.0);
    }

    #[test]
    fn zero_mass_no_wound() {
        let r = evaluate(400.0, 0.0, 0.00901, "fmj");
        assert_eq!(r.penetration_depth_m, 0.0);
    }

    #[test]
    fn below_threshold_no_wound() {
        let r = evaluate(10.0, 8.0, 0.00901, "fmj");
        assert_eq!(r.penetration_depth_m, 0.0);
    }

    #[test]
    fn high_velocity_increases_cavity() {
        let slow = evaluate(400.0, 8.0, 0.00901, "fmj");
        let fast = evaluate(600.0, 8.0, 0.00901, "fmj");
        assert!(
            fast.temp_cavity_diameter_m > slow.temp_cavity_diameter_m,
            "Higher velocity should produce larger temporary cavity"
        );
    }

    // ── Wound profile ──────────────────────────────────────────────────

    #[test]
    fn wound_profile_returns_samples() {
        let profile = wound_profile(930.0, 4.0, 0.00556, "fmj", 10);
        assert!(!profile.is_empty(), "Profile should have samples");
        assert_eq!(profile.len(), 10, "Should return exactly 10 samples");
        for i in 1..profile.len() {
            assert!(
                profile[i].0 > profile[i - 1].0,
                "Depth should increase monotonically"
            );
        }
    }

    #[test]
    fn wound_profile_handgun() {
        let profile = wound_profile(360.0, 8.0, 0.00901, "fmj", 5);
        assert_eq!(profile.len(), 5);
        for i in 1..profile.len() {
            assert!(
                profile[i].2 <= profile[i - 1].2 + 1e-6,
                "Handgun dE/dx should decrease with depth"
            );
        }
    }

    #[test]
    fn wound_profile_empty_for_no_penetration() {
        let profile = wound_profile(0.0, 8.0, 0.00901, "fmj", 10);
        assert!(profile.is_empty(), "Should be empty for no penetration");
    }

    // ── Bone interaction tests ──────────────────────────────────────────────

    #[test]
    fn bone_impact_changes_wound_characteristics() {
        let no_bone = evaluate_extended(850.0, 9.5, 0.00782, "fmj", None);
        let with_bone = evaluate_extended(
            850.0,
            9.5,
            0.00782,
            "fmj",
            Some((BoneType::Femur, 10.0, 0.05)),
        );
        assert!(
            (with_bone.temp_cavity_diameter_m - no_bone.temp_cavity_diameter_m).abs() < 0.15,
            "Bone should affect cavity: no_bone={:.4}, with_bone={:.4}",
            no_bone.temp_cavity_diameter_m,
            with_bone.temp_cavity_diameter_m
        );
        assert!(
            with_bone.bone_penetrated || with_bone.bone_energy_j > 100.0,
            "Bone impact should either penetrate or deposit energy"
        );
        if with_bone.bone_penetrated {
            assert!(
                with_bone.bone_fragments > 0,
                "Penetrating bone impact should generate fragments"
            );
        }
    }

    #[test]
    fn evaluate_extended_no_bone_matches_evaluate() {
        let base = evaluate(930.0, 4.0, 0.00556, "fmj");
        let ext = evaluate_extended(930.0, 4.0, 0.00556, "fmj", None);
        assert!((base.penetration_depth_m - ext.penetration_depth_m).abs() < 0.001);
        assert!((base.temp_cavity_diameter_m - ext.temp_cavity_diameter_m).abs() < 0.001);
        assert!((base.energy_deposited_j - ext.energy_deposited_j).abs() < 0.001);
    }

    #[test]
    fn evaluate_extended_bone_stops_projectile() {
        let result = evaluate_extended(
            300.0,
            2.6,
            0.00556,
            "fmj",
            Some((BoneType::Femur, 0.0, 0.04)),
        );
        assert!(!result.bone_penetrated, ".22 LR should not penetrate femur");
        assert_eq!(
            result.bone_fragments, 0,
            "No bone fragments if projectile stopped"
        );
    }

    // ── ACE3 Medical Classification tests ──────────────────────────────────

    #[test]
    fn ace3_m855_center_mass() {
        let wound = evaluate(930.0, 4.0, 0.00556, "fmj");
        let ace3 = classify_ace3_wound(&wound, 930.0, 4.0, "fmj", "thorax", true, None);
        assert!(
            matches!(ace3.wound_type, ACE3WoundType::AvulsionWound),
            "M855 center mass should be avulsion: {:?}",
            ace3.wound_type
        );
        assert!(ace3.blood_loss_ml_per_s > 5.0, "Blood loss > 5 ml/s");
    }

    #[test]
    fn ace3_9mm_to_limb() {
        let wound = evaluate(360.0, 8.0, 0.00901, "fmj");
        let ace3 = classify_ace3_wound(&wound, 360.0, 8.0, "fmj", "limb", true, None);
        assert_eq!(ace3.wound_type, ACE3WoundType::BulletWound);
        assert!(
            ace3.blood_loss_ml_per_s < 8.0,
            "9mm to limb blood loss reasonable: {:.1}",
            ace3.blood_loss_ml_per_s
        );
        assert!(
            ace3.pain_level <= 7,
            "9mm limb pain should be moderate: {}",
            ace3.pain_level
        );
    }

    #[test]
    fn ace3_762mm_m80_to_thorax() {
        let wound = evaluate(850.0, 9.5, 0.00782, "fmj");
        let ace3 = classify_ace3_wound(&wound, 850.0, 9.5, "fmj", "thorax", true, None);
        assert!(
            matches!(
                ace3.wound_type,
                ACE3WoundType::BulletWound | ACE3WoundType::AvulsionWound
            ),
            "M80 should be bullet or avulsion wound: {:?}",
            ace3.wound_type
        );
        assert!(ace3.wound_size >= 4, "Wound size should be >= 4");
    }

    #[test]
    fn ace3_22lr_to_head() {
        let wound = evaluate(330.0, 2.6, 0.00556, "fmj");
        let ace3 = classify_ace3_wound(&wound, 330.0, 2.6, "fmj", "head", true, None);
        assert!(
            ace3.immediate_incapacitation,
            ".22 LR to head should be immediately incapacitating"
        );
        assert!(ace3.pain_level >= 7, "Head wound pain should be severe");
    }

    #[test]
    fn ace3_babt_contusion() {
        let wound = WoundResult {
            penetration_depth_m: 0.0,
            temp_cavity_diameter_m: 0.02,
            perm_cavity_diameter_m: 0.005,
            energy_deposited_j: 30.0,
            peak_edep_j_per_cm: 5.0,
            yawed: false,
            yaw_depth_m: 0.0,
            frag_mass_g: 0.0,
            bone_penetrated: false,
            bone_fragments: 0,
            bone_energy_j: 0.0,
        };
        let ace3 = classify_ace3_wound(&wound, 400.0, 8.0, "fmj", "thorax", false, Some("aramid"));
        assert_eq!(ace3.wound_type, ACE3WoundType::ContusionWound);
    }

    #[test]
    fn ace3_fragment_shrapnel_wound() {
        let wound = WoundResult {
            penetration_depth_m: 0.05,
            temp_cavity_diameter_m: 0.01,
            perm_cavity_diameter_m: 0.003,
            energy_deposited_j: 80.0,
            peak_edep_j_per_cm: 10.0,
            yawed: false,
            yaw_depth_m: 0.0,
            frag_mass_g: 0.0,
            bone_penetrated: true,
            bone_fragments: 3,
            bone_energy_j: 50.0,
        };
        let ace3 = classify_ace3_wound(&wound, 600.0, 2.0, "fmj", "limb", true, None);
        assert_eq!(ace3.wound_type, ACE3WoundType::ShrapnelWound);
    }

    #[test]
    fn ace3_338_lapua_in_limb() {
        let wound = evaluate(880.0, 16.2, 0.00858, "fmj");
        let ace3 = classify_ace3_wound(&wound, 880.0, 16.2, "fmj", "limb", true, None);
        assert!(
            matches!(
                ace3.wound_type,
                ACE3WoundType::AvulsionWound | ACE3WoundType::BulletWound
            ),
            ".338 Lapua should cause avulsion wound: {:?}",
            ace3.wound_type
        );
        assert!(ace3.blood_loss_ml_per_s > 8.0, "Blood loss should be high");
    }

    // ── Multi-Projectile / Shotgun tests ───────────────────────────────────

    #[test]
    fn buckshot_00_at_10m() {
        let config = shotgun_config("12ga_buckshot_00");
        let result = evaluate_multi_impact(&config, 10.0, 500.0, 0.5);
        assert!(
            result.hits >= 5,
            "At 10m most buck pellets should hit torso: {} hits",
            result.hits
        );
        assert!(result.combined_energy_j > 1000.0, "Combined KE > 1000 J");
    }

    #[test]
    fn buckshot_00_at_50m() {
        let config = shotgun_config("12ga_buckshot_00");
        let result = evaluate_multi_impact(&config, 50.0, 500.0, 0.5);
        assert!(
            result.hits < 8,
            "At 50m fewer pellets should hit: {} hits",
            result.hits
        );
    }

    #[test]
    fn birdshot_at_25m() {
        let config = shotgun_config("12ga_birdshot_7.5");
        let result = evaluate_multi_impact(&config, 25.0, 500.0, 0.5);
        assert!(
            result.hits > 10,
            "Birdshot at 25m should have many hits: {}",
            result.hits
        );
    }

    #[test]
    fn duplex_at_300m() {
        let config = shotgun_config("duplex_556");
        let result = evaluate_multi_impact(&config, 300.0, 500.0, 0.5);
        assert!(
            result.hits >= 1,
            "Duplex at 300m both should hit: {} hits",
            result.hits
        );
    }

    #[test]
    fn flechette_at_25m() {
        let config = shotgun_config("flechette_12ga");
        let result = evaluate_multi_impact(&config, 25.0, 500.0, 0.5);
        assert!(
            result.hits > 5,
            "Flechette at 25m should have multiple hits: {}",
            result.hits
        );
    }

    #[test]
    fn shotgun_config_types() {
        let cfg00 = shotgun_config("12ga_buckshot_00");
        assert_eq!(cfg00.pellet_count, 8);
        assert!((cfg00.pellet_mass_g - 3.5).abs() < 0.1);

        let cfg_duplex = shotgun_config("duplex_556");
        assert_eq!(cfg_duplex.pellet_count, 2);

        let cfg_flechette = shotgun_config("flechette");
        assert_eq!(cfg_flechette.pellet_count, 20);
    }

    #[test]
    fn multi_impact_zero_range_all_hit() {
        let config = shotgun_config("12ga_buckshot_00");
        let result = evaluate_multi_impact(&config, 0.0, 500.0, 0.5);
        assert_eq!(result.hits, config.pellet_count, "At 0m all pellets hit");
    }

    #[test]
    fn multi_impact_empty_config() {
        let config = MultiProjectileConfig {
            pellet_count: 0,
            pellet_mass_g: 0.0,
            pellet_diameter_mm: 0.0,
            muzzle_velocity_ms: 0.0,
            spread_moa: 0.0,
            projectile_type: "shot",
        };
        let result = evaluate_multi_impact(&config, 10.0, 500.0, 0.5);
        assert_eq!(result.hits, 0);
        assert!(result.pellet_wounds.is_empty());
    }
}
