// ABE - Vehicle Component Damage Model
//
// Evaluates post-penetration damage to vehicle components: ammo rack cookoff,
// fuel tank fire/explosion, engine kill/fire, transmission damage, and
// crew incapacitation from behind-armour debris (BAD / spall).
//
// Called after a projectile has perforated the main armour — the caller
// provides residual velocity, energy, spall/BAD data, and the component
// configuration.
//
// References:
//   - MIL-HDBK-799 (Vehicle Vulnerability — Component Kill Criteria)
//   - BRL CR 341 (Critical Energy Criteria for Vehicle Components)
//   - NATO STANAG 4569 Annex D (Crew Vulnerability to Spall)
//   - Fairlie J.P., "Behind Armour Debris Modelling" (DERA)
//   - DMSS (Defence Modelling & Simulation) Handbook, UK MoD
//   - Held M., "Cookoff Thresholds for Stored Munitions" (Propellants,
//     Explosives, Pyrotechnics, Vol 15)
//   - MIL-STD-2105D (Hazard Assessment for Ammunition Stowage)

// ── Component & stored-material types ──────────────────────────────────────────

/// Types of ammunition stored in a vehicle component.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum AmmoStoredType {
    /// Small-arms cartridges (5.56, 7.62, 12.7 mm) — cookoff ~5 kJ threshold.
    SmallArms,
    /// Cannon shells (20–40 mm HE/I) — cookoff ~20 kJ.
    CannonShells,
    /// Shaped-charge warheads (ATGM, HEAT) — cookoff ~1 kJ (sensitive explosive).
    HEAT,
    /// Missile rocket motors (stored propellant) — cookoff ~10 kJ.
    Missile,
    /// Mixed stowage — uses the lowest threshold present.
    Mixed,
}

/// Fuel types carried in vehicle fuel tanks.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum FuelType {
    /// Diesel — low volatility, hardest to ignite.
    Diesel,
    /// Petrol (gasoline) — high volatility, easiest to ignite.
    Petrol,
    /// JP-8 / kerosene-based turbine fuel — intermediate.
    JP8,
}

/// Engine type — determines block mass and fire behaviour.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum EngineType {
    /// Heavy diesel engine (armoured vehicles, ~800 kg).
    Diesel,
    /// Petrol engine (light vehicles, ~200 kg).
    Petrol,
    /// Gas turbine (MBTs, ~600 kg).
    Turbine,
    /// Electric motor (hybrid/EVs, ~150 kg).
    Electric,
}

/// Protection level for crew positions behind armour.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CrewProtection {
    /// Unprotected — bare steel behind armour, no spall liner.
    None,
    /// Light liner — thin Kevlar/twaron sheet.
    Light,
    /// Full spall liner — thick aramid or UHMWPE layer.
    SpallLiner,
    /// Heavy protection — encapsulated crew pod with spaced armour.
    Heavy,
}

/// Vehicle component type — the high-level discriminator.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ComponentType {
    /// Ammunition stowage (ready-rack, hull stowage).
    AmmoRack { ammo_type: AmmoStoredType },
    /// Fuel tank (integral, armoured, or external).
    FuelTank { fuel_type: FuelType },
    /// Engine / powerpack.
    Engine { engine_type: EngineType },
    /// Gearbox / final drive.
    Transmission,
    /// Crew position (driver, gunner, commander, loader).
    Crew { protection_level: CrewProtection },
}

// ── Configuration & result structs ────────────────────────────────────────────

/// Configuration describing a single vehicle component.
#[derive(Debug, Clone)]
pub struct ComponentConfig {
    /// Which component and its sub-type.
    pub component: ComponentType,
    /// Local armour protection thickness in mm (0 if unarmoured).
    pub local_armor_thickness_mm: f64,
    /// Armour material type (same strings as penetration::material_factor).
    pub local_armor_material: &'static str,
    /// Local armour angle from normal in degrees (0 = perpendicular).
    pub local_angle_deg: f64,
}

/// Result of evaluating post-penetration damage to a vehicle component.
#[derive(Debug, Clone)]
pub struct ComponentDamageResult {
    /// Component has been completely destroyed (e.g. ammo cookoff).
    pub component_destroyed: bool,
    /// Component is disabled (fuel tank leaking, engine seized).
    pub component_disabled: bool,
    /// A fire has started in this component.
    pub fire_started: bool,
    /// The component has exploded (ammo cookoff or fuel vapour explosion).
    pub explosion: bool,
    /// Number of secondary fragments generated by this component failure
    /// (e.g. ammo rack fragments, flywheel fragments).
    pub secondary_fragments: i32,
    /// Residual kinetic energy of the projectile after damaging this
    /// component (it may continue into adjacent components).
    pub residual_energy_j: f64,
    /// Fraction of vehicle mobility lost due to this damage (0.0–1.0).
    pub mobility_loss_fraction: f64,
    /// Number of crew casualties in this crew position.
    pub crew_casualties: i32,
}

// ── Cookoff thresholds ─────────────────────────────────────────────────────────

/// Cookoff energy thresholds by ammo type (J).
fn cookoff_threshold_j(ammo: AmmoStoredType) -> f64 {
    match ammo {
        AmmoStoredType::SmallArms => 5_000.0,
        AmmoStoredType::CannonShells => 20_000.0,
        AmmoStoredType::HEAT => 1_000.0,
        AmmoStoredType::Missile => 10_000.0,
        // Mixed: use the lowest to be conservative
        AmmoStoredType::Mixed => 1_000.0,
    }
}

/// Scale factor for ammo type sensitivity to cookoff (higher = more sensitive).
fn cookoff_sensitivity(ammo: AmmoStoredType) -> f64 {
    match ammo {
        AmmoStoredType::SmallArms => 1.0,
        AmmoStoredType::CannonShells => 0.8,
        AmmoStoredType::HEAT => 2.0,
        AmmoStoredType::Missile => 1.5,
        AmmoStoredType::Mixed => 1.2,
    }
}

// ── Fuel ignition thresholds ──────────────────────────────────────────────────

/// Minimum residual energy to start a fuel leak (J).
const FUEL_LEAK_THRESHOLD_J: f64 = 200.0;

/// Energy threshold for fuel vapour explosion (above leak threshold).
fn fuel_explosion_threshold_j(fuel: FuelType) -> f64 {
    match fuel {
        FuelType::Petrol => 2_000.0,
        FuelType::JP8 => 5_000.0,
        FuelType::Diesel => 8_000.0,
    }
}

/// Base probability of fire per kJ of residual energy, without incendiary.
fn fuel_fire_base_prob(fuel: FuelType) -> f64 {
    match fuel {
        FuelType::Petrol => 0.08,
        FuelType::JP8 => 0.04,
        FuelType::Diesel => 0.02,
    }
}

// ── Engine constants ──────────────────────────────────────────────────────────

/// Engine block mass (kg) by type — used to compute energy absorption.
fn engine_block_mass_kg(engine: EngineType) -> f64 {
    match engine {
        EngineType::Diesel => 800.0,
        EngineType::Petrol => 200.0,
        EngineType::Turbine => 600.0,
        EngineType::Electric => 150.0,
    }
}

/// Engine fire base probability (per kJ of absorbed energy).
fn engine_fire_prob(engine: EngineType) -> f64 {
    match engine {
        EngineType::Diesel => 0.01,
        EngineType::Petrol => 0.05,
        EngineType::Turbine => 0.03,
        EngineType::Electric => 0.005,
    }
}

// ── Crew vulnerability constants ──────────────────────────────────────────────

/// Spall liner protection factor (multiplier on fragment kinetic energy
/// required to cause injury).
fn spall_protection_factor(protection: CrewProtection) -> f64 {
    match protection {
        CrewProtection::None => 1.0,
        CrewProtection::Light => 2.5,
        CrewProtection::SpallLiner => 5.0,
        CrewProtection::Heavy => 10.0,
    }
}

/// Minimum fragment KE (J) to cause a crew casualty.
const CREW_INJURY_THRESHOLD_J: f64 = 80.0;

// ── Projectile type modifiers ─────────────────────────────────────────────────

/// Fire multiplier: incendiary and API rounds increase fire probability.
fn projectile_fire_multiplier(proj_type: &str) -> f64 {
    match proj_type.to_lowercase().as_str() {
        "incendiary" | "i" => 3.0,
        "api" | "ap_i" => 2.5,
        "hei" | "he_i" => 4.0,
        "hei_t" | "he_i_t" => 4.0,
        "tracer" | "t" | "t45" | "t46" => 1.3,
        _ => 1.0,
    }
}

/// Fragmentation multiplier: some rounds produce more secondary fragments.
fn projectile_frag_multiplier(proj_type: &str) -> f64 {
    match proj_type.to_lowercase().as_str() {
        "incendiary" | "i" => 1.5,
        "api" | "ap_i" => 1.3,
        "hei" | "he_i" => 2.0,
        "hei_t" | "he_i_t" => 2.0,
        "heat" | "he" => 1.8,
        _ => 1.0,
    }
}

// ── Core evaluation ───────────────────────────────────────────────────────────

/// Evaluate damage to a vehicle component after armour penetration.
///
/// # Arguments
/// * `component` — The component configuration (type, local armour, material).
/// * `residual_velocity_ms` — Projectile velocity after penetrating the
///   vehicle's main armour (m/s).  Pass 0.0 if the round did not penetrate.
/// * `projectile_mass_g` — Projectile mass in grams.
/// * `projectile_type` — Construction type string: "ball", "ap", "apds",
///   "incendiary", "api", "hei", "tracer", etc.
/// * `caliber_mm` — Projectile calibre in millimetres.
/// * `spall_fragments` — Number of behind-armour debris (BAD) fragments
///   from the armour penetration (use `PenetrationResult.spall_fragments`).
/// * `bad_spray_angle_deg` — Spray cone half-angle of BAD fragments
///   (use `PenetrationResult.bad_spray_angle_deg`).
/// * `bad_total_mass_g` — Total mass of BAD fragments
///   (use `PenetrationResult.bad_total_mass_g`).
///
/// # Returns
/// `ComponentDamageResult` describing the damage state.
pub fn evaluate_component_damage(
    component: &ComponentConfig,
    residual_velocity_ms: f64,
    projectile_mass_g: f64,
    projectile_type: &str,
    caliber_mm: f64,
    spall_fragments: i32,
    bad_spray_angle_deg: f64,
    bad_total_mass_g: f64,
) -> ComponentDamageResult {
    // Compute residual kinetic energy
    let mass_kg = projectile_mass_g / 1000.0;
    let residual_ke_j = 0.5 * mass_kg * residual_velocity_ms.powi(2);

    // If residual velocity is below threshold, no meaningful damage
    if residual_velocity_ms < 50.0 && spall_fragments == 0 {
        return ComponentDamageResult {
            component_destroyed: false,
            component_disabled: false,
            fire_started: false,
            explosion: false,
            secondary_fragments: 0,
            residual_energy_j: residual_ke_j,
            mobility_loss_fraction: 0.0,
            crew_casualties: 0,
        };
    }

    let proj_mult = projectile_fire_multiplier(projectile_type);
    let frag_mult = projectile_frag_multiplier(projectile_type);

    match component.component {
        ComponentType::AmmoRack { ammo_type } => evaluate_ammo_rack(
            ammo_type,
            residual_ke_j,
            residual_velocity_ms,
            caliber_mm,
            proj_mult,
            frag_mult,
        ),
        ComponentType::FuelTank { fuel_type } => evaluate_fuel_tank(
            fuel_type,
            residual_ke_j,
            residual_velocity_ms,
            component,
            proj_mult,
            frag_mult,
        ),
        ComponentType::Engine { engine_type } => {
            evaluate_engine(engine_type, residual_ke_j, residual_velocity_ms, proj_mult)
        }
        ComponentType::Transmission => {
            evaluate_transmission(residual_ke_j, residual_velocity_ms, caliber_mm)
        }
        ComponentType::Crew { protection_level } => evaluate_crew(
            protection_level,
            residual_ke_j,
            residual_velocity_ms,
            spall_fragments,
            bad_spray_angle_deg,
            bad_total_mass_g,
            caliber_mm,
        ),
    }
}

// ── Per-component evaluators ───────────────────────────────────────────────────

/// Evaluate ammo rack cookoff.
fn evaluate_ammo_rack(
    ammo_type: AmmoStoredType,
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    _caliber_mm: f64,
    proj_mult: f64,
    frag_mult: f64,
) -> ComponentDamageResult {
    let threshold = cookoff_threshold_j(ammo_type);
    let sensitivity = cookoff_sensitivity(ammo_type);

    if residual_ke_j < threshold {
        // Not enough energy for cookoff — projectile passes through
        // with partial energy absorption from internal structure.
        let absorbed_frac = 0.1;
        return ComponentDamageResult {
            component_destroyed: false,
            component_disabled: false,
            fire_started: false,
            explosion: false,
            secondary_fragments: (2.0 * frag_mult) as i32,
            residual_energy_j: residual_ke_j * (1.0 - absorbed_frac),
            mobility_loss_fraction: 0.0,
            crew_casualties: 0,
        };
    }

    // Energy above threshold: probability of cookoff scales with
    // energy density and sensitivity.
    let energy_ratio = (residual_ke_j / threshold).clamp(1.0, 10.0);
    let cookoff_prob = (1.0 - (-sensitivity * (energy_ratio - 1.0)).exp()).clamp(0.0, 1.0);

    // If cookoff occurs, it's a catastrophic high-order explosion.
    let explosion = rand_threshold(cookoff_prob);

    if explosion {
        // Catastrophic cookoff: all residual energy released as explosion.
        // Secondary fragments from ammo cases, links, vehicle structure.
        let frag_count = (50.0 * frag_mult + 30.0 * (energy_ratio - 1.0)).round() as i32;
        ComponentDamageResult {
            component_destroyed: true,
            component_disabled: true,
            fire_started: true,
            explosion: true,
            secondary_fragments: frag_count.clamp(10, 200),
            residual_energy_j: residual_ke_j * 0.05, // almost none left
            mobility_loss_fraction: 1.0,
            crew_casualties: 0,
        }
    } else {
        // No cookoff, but ammo may be damaged / burning propellant.
        // ponytail: simple fire check, revisit with stowed-round cookoff model
        let fire_prob = 0.05 * proj_mult * sensitivity * (energy_ratio - 1.0).min(1.0);
        let fire = rand_threshold(fire_prob.clamp(0.0, 1.0));
        ComponentDamageResult {
            component_destroyed: false,
            component_disabled: fire,
            fire_started: fire,
            explosion: false,
            secondary_fragments: (5.0 * frag_mult) as i32,
            residual_energy_j: residual_ke_j * 0.7,
            mobility_loss_fraction: 0.0,
            crew_casualties: 0,
        }
    }
}

/// Evaluate fuel tank penetration.
fn evaluate_fuel_tank(
    fuel_type: FuelType,
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    component: &ComponentConfig,
    proj_mult: f64,
    frag_mult: f64,
) -> ComponentDamageResult {
    if residual_ke_j < FUEL_LEAK_THRESHOLD_J {
        // Projectile failed to perforate tank wall.
        return ComponentDamageResult {
            component_destroyed: false,
            component_disabled: false,
            fire_started: false,
            explosion: false,
            secondary_fragments: 0,
            residual_energy_j: residual_ke_j,
            mobility_loss_fraction: 0.0,
            crew_casualties: 0,
        };
    }

    // Fuel tank is always leaking if perforated (fuel is liquid).
    // The question is whether it ignites.
    let explosion_threshold = fuel_explosion_threshold_j(fuel_type);
    let base_prob = fuel_fire_base_prob(fuel_type);

    // Energy scaling: more energy → higher fire probability.
    let energy_factor = (residual_ke_j / 1000.0).clamp(1.0, 20.0);
    let fire_prob = (base_prob * energy_factor * proj_mult).clamp(0.0, 1.0);
    let fire = rand_threshold(fire_prob);

    // Explosion occurs if residual energy is well above threshold AND
    // fuel type is volatile enough. Fuel vapour explosion is a separate
    // event from fire (higher threshold).
    let explosion_prob = if residual_ke_j >= explosion_threshold {
        let vapor_ratio = ((residual_ke_j - explosion_threshold) / 10_000.0).clamp(0.0, 3.0);
        (0.15 * vapor_ratio * proj_mult).clamp(0.0, 0.9)
    } else {
        0.0
    };
    let explosion = rand_threshold(explosion_prob);

    // Energy absorption: fuel tank wall and fuel itself absorb some energy.
    let armor = component.local_armor_thickness_mm.max(1.0);
    let absorbed_by_tank = (armor * 10.0).min(residual_ke_j * 0.3);
    let residual = residual_ke_j - absorbed_by_tank;

    let frag_count = if explosion {
        (20.0 * frag_mult) as i32
    } else if fire {
        (5.0 * frag_mult) as i32
    } else {
        (2.0 * frag_mult) as i32
    };

    // Fuel tank is leaking whenever perforated (residual energy above
    // leak threshold).  Leaking fuel always disables the tank — the
    // question is only whether it ignites or explodes.
    let leaking = true;
    ComponentDamageResult {
        component_destroyed: explosion,
        component_disabled: leaking || fire || explosion,
        fire_started: fire || explosion,
        explosion,
        secondary_fragments: frag_count,
        residual_energy_j: residual.max(0.0),
        mobility_loss_fraction: if explosion { 1.0 } else { 0.0 },
        crew_casualties: 0,
    }
}

/// Evaluate engine damage.
fn evaluate_engine(
    engine_type: EngineType,
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    proj_mult: f64,
) -> ComponentDamageResult {
    let block_mass = engine_block_mass_kg(engine_type);

    // Energy absorbed by engine block. The block absorbs energy through
    // plastic deformation, cracking, and component damage.
    // ponytail: linear energy absorption model, upgrade to section-based
    // (cylinder head → block → crankcase) if per-system kill matters.
    let max_absorbed_j = block_mass * 150.0; // ~120 kJ for 800 kg diesel
    let absorbed_j = residual_ke_j.min(max_absorbed_j);
    let absorbed_fraction = absorbed_j / max_absorbed_j;

    // Gradual degradation: mobility loss scales with absorbed fraction.
    // Partial power loss kicks in before full kill.
    let mobility_loss = if absorbed_fraction < 0.15 {
        // Minor damage — some power loss
        absorbed_fraction * 0.5
    } else if absorbed_fraction < 0.40 {
        // Moderate damage — significant power loss, possible seize
        0.3 + (absorbed_fraction - 0.15) * 1.2
    } else {
        // Severe damage — engine stopped or seized
        let severe = 0.6 + (absorbed_fraction - 0.40) * 1.0;
        severe.min(1.0)
    };

    let disabled = absorbed_fraction >= 0.40;
    let destroyed = absorbed_fraction >= 0.85;

    // Fire from fuel/oil ignition on hot engine surfaces.
    let fire_prob = if absorbed_fraction > 0.2 {
        (engine_fire_prob(engine_type) * absorbed_fraction * 10.0 * proj_mult).clamp(0.0, 0.6)
    } else {
        0.0
    };
    let fire = rand_threshold(fire_prob);

    // Residual energy after passing through engine:
    // The projectile loses energy proportional to what the block absorbs.
    let residual = (residual_ke_j - absorbed_j).max(0.0);

    // Secondary fragments: flywheel / casing fragments if destroyed.
    let frags = if destroyed {
        15
    } else if absorbed_fraction > 0.3 {
        5
    } else {
        0
    };

    ComponentDamageResult {
        component_destroyed: destroyed,
        component_disabled: disabled,
        fire_started: fire,
        explosion: false,
        secondary_fragments: frags,
        residual_energy_j: residual,
        mobility_loss_fraction: mobility_loss,
        crew_casualties: 0,
    }
}

/// Evaluate transmission damage.
fn evaluate_transmission(
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    _caliber_mm: f64,
) -> ComponentDamageResult {
    // Transmission is compact with heavy gear clusters.
    // ponytail: single-box model, upgrade to gear-by-gear if individual
    // gear ratios matter.
    let max_absorbed_j = 60_000.0; // ~60 kJ to disable gearbox
    let absorbed_j = residual_ke_j.min(max_absorbed_j);
    let absorbed_fraction = absorbed_j / max_absorbed_j;

    let disabled = absorbed_fraction >= 0.35;
    let destroyed = absorbed_fraction >= 0.75;

    let mobility_loss = if destroyed {
        1.0
    } else if disabled {
        0.8
    } else {
        absorbed_fraction * 0.5
    };

    let residual = (residual_ke_j - absorbed_j).max(0.0);

    ComponentDamageResult {
        component_destroyed: destroyed,
        component_disabled: disabled,
        fire_started: false,
        explosion: false,
        secondary_fragments: if destroyed { 10 } else { 0 },
        residual_energy_j: residual,
        mobility_loss_fraction: mobility_loss,
        crew_casualties: 0,
    }
}

/// Evaluate crew injury from behind-armour debris (BAD / spall).
fn evaluate_crew(
    protection_level: CrewProtection,
    residual_ke_j: f64,
    _residual_velocity_ms: f64,
    spall_fragments: i32,
    bad_spray_angle_deg: f64,
    bad_total_mass_g: f64,
    _caliber_mm: f64,
) -> ComponentDamageResult {
    let protection = spall_protection_factor(protection_level);

    // Effective fragment KE = total BAD mass kinetic energy / fragment count,
    // reduced by spall liner protection.
    if spall_fragments <= 0 || bad_total_mass_g <= 0.0 {
        // No BAD fragments, but the projectile itself may still hit crew.
        // ponytail: direct projectile hit on crew — full KE, no spall
        return ComponentDamageResult {
            component_destroyed: false,
            component_disabled: false,
            fire_started: false,
            explosion: false,
            secondary_fragments: 0,
            residual_energy_j: residual_ke_j,
            mobility_loss_fraction: 0.0,
            crew_casualties: if residual_ke_j > CREW_INJURY_THRESHOLD_J {
                1
            } else {
                0
            },
        };
    }

    // BAD fragments distribute total mass. Average fragment KE:
    let avg_frag_mass_kg = bad_total_mass_g / spall_fragments as f64 / 1000.0;
    // Fragment velocity is approximately the residual velocity of the
    // projectile, reduced by spray angle spreading.
    let vel_factor = (bad_spray_angle_deg.max(5.0) / 45.0).clamp(0.2, 1.0);
    let frag_vel = _residual_velocity_ms * vel_factor.max(100.0 / _residual_velocity_ms.max(100.0));

    // Each fragment's kinetic energy, divided by protection factor.
    let frag_ke_j = 0.5 * avg_frag_mass_kg * frag_vel.powi(2) / protection;

    // Number of casualties: fragments that exceed injury threshold.
    let casualties = if frag_ke_j > CREW_INJURY_THRESHOLD_J {
        // Higher KE → more fragments cause injury.
        let inj_prob = (1.0 - CREW_INJURY_THRESHOLD_J / frag_ke_j).clamp(0.0, 1.0);
        (spall_fragments as f64 * inj_prob).round() as i32
    } else {
        // Fragments below threshold may still cause minor injury.
        // Only count ~10% as casualties if near threshold.
        if frag_ke_j > CREW_INJURY_THRESHOLD_J * 0.5 {
            1
        } else {
            0
        }
    };

    // Crew compartment is not "destroyed" but the crew position is
    // effectively disabled if all occupants are casualties.
    let position_disabled = casualties >= 1;

    ComponentDamageResult {
        component_destroyed: false,
        component_disabled: position_disabled,
        fire_started: false,
        explosion: false,
        secondary_fragments: 0,
        residual_energy_j: residual_ke_j * 0.9, // crew absorbs little energy
        mobility_loss_fraction: 0.0,
        crew_casualties: casualties.min(3), // max 3 per crew position
    }
}

// ── Refined crew injury model ──────────────────────────────────────────────────

/// Category of injury severity.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum InjurySeverity {
    /// No injury.
    None,
    /// Minor wound (fragment lodged in non-critical area, soldier combat-effective with treatment).
    Minor,
    /// Serious wound (fragment hit vital area, requires evacuation, significant combat power loss).
    Serious,
    /// Fatal wound (immediately incapacitating or lethal).
    Fatal,
}

/// Body region hit by behind-armour debris.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BodyRegion {
    /// Head/neck — ~12% of presented area, high lethality.
    HeadNeck,
    /// Thorax/chest — ~16% of area, high lethality.
    Thorax,
    /// Abdomen — ~11% of area, moderate lethality.
    Abdomen,
    /// Arms — ~22% of area, low lethality.
    Arms,
    /// Legs — ~39% of area, low lethality.
    Legs,
}

impl BodyRegion {
    /// All body regions in order of descending lethality, for iteration.
    pub const ALL: [BodyRegion; 5] = [
        BodyRegion::HeadNeck,
        BodyRegion::Thorax,
        BodyRegion::Abdomen,
        BodyRegion::Arms,
        BodyRegion::Legs,
    ];
}

/// Result of a refined crew injury evaluation.
#[derive(Debug, Clone)]
pub struct CrewInjuryResult {
    /// Total number of fragments that struck the crew position.
    pub total_impacts: i32,
    /// Number of fatal wounds.
    pub fatal_wounds: i32,
    /// Number of serious wounds.
    pub serious_wounds: i32,
    /// Number of minor wounds.
    pub minor_wounds: i32,
    /// Number of crew members incapacitated.
    pub crew_incapacitated: i32,
    /// Detailed breakdown by body region.
    pub region_breakdown: Vec<BodyRegionInjury>,
    /// Probability of at least one fatal hit (>0.5 = likely fatality).
    pub fatal_hit_probability: f64,
}

/// Injury breakdown for a single body region.
#[derive(Debug, Clone)]
pub struct BodyRegionInjury {
    /// Which body region this breakdown covers.
    pub region: BodyRegion,
    /// Number of fragment impacts in this region.
    pub fragment_impacts: i32,
    /// Number of fatal hits in this region.
    pub fatal_hits: i32,
    /// Number of serious hits in this region.
    pub serious_hits: i32,
    /// Number of minor hits in this region.
    pub minor_hits: i32,
}

/// Body region lethality: probability a hit to this region is fatal,
/// given a fragment of at least threshold KE.
///
/// Returns `(fatal_prob, serious_prob, minor_prob)` summing to ≤ 1.0.
fn region_lethality(region: BodyRegion, fragment_ke_j: f64) -> (f64, f64, f64) {
    let region_params: (f64, f64, f64) = match region {
        BodyRegion::HeadNeck => (0.85, 0.10, 0.05),
        BodyRegion::Thorax => (0.60, 0.25, 0.15),
        BodyRegion::Abdomen => (0.30, 0.40, 0.30),
        BodyRegion::Arms => (0.05, 0.25, 0.70),
        BodyRegion::Legs => (0.02, 0.18, 0.80),
    };

    // Scale by KE: below CREW_INJURY_THRESHOLD_J (80 J), reduce severity
    let ke_factor = (fragment_ke_j / CREW_INJURY_THRESHOLD_J).clamp(0.0, 1.0);
    if ke_factor < 1.0 {
        // Below threshold: mostly minor or none
        (
            0.0,
            region_params.1 * ke_factor * 0.3,
            region_params.2 * ke_factor,
        )
    } else {
        // Above threshold: full lethality, scaled by log(KE/threshold)
        let severity = 1.0 + 0.5 * (fragment_ke_j / CREW_INJURY_THRESHOLD_J).ln().max(0.0);
        let fatal = region_params.0.min(1.0_f64);
        let serious = (region_params.1 * severity.min(2.0)).min(1.0 - fatal);
        (fatal, serious, region_params.2)
    }
}

/// Body region area fraction of total presented body area.
fn region_area_fraction(region: BodyRegion) -> f64 {
    match region {
        BodyRegion::HeadNeck => 0.12,
        BodyRegion::Thorax => 0.16,
        BodyRegion::Abdomen => 0.11,
        BodyRegion::Arms => 0.22,
        BodyRegion::Legs => 0.39,
    }
}

/// Generate a mass distribution of BAD fragments using a power-law model.
///
/// Real behind-armour debris follows approximately a Mott distribution:
///   dN/dm = C · m^(-β)  where β ≈ 2.0 for armour steel
///
/// Returns a vector of fragment masses in kg.
fn generate_fragment_masses(total_mass_g: f64, num_fragments: i32, is_apfsds: bool) -> Vec<f64> {
    let count = num_fragments.max(1);
    let total_kg = total_mass_g / 1000.0;

    if count <= 1 {
        return vec![total_kg];
    }

    // Power-law exponent: APFSDS produces finer fragments (β ≈ 2.2)
    // vs. conventional rounds (β ≈ 1.8)
    let beta = if is_apfsds { 2.2 } else { 1.8 };

    let mut masses: Vec<f64> = Vec::with_capacity(count as usize);

    // Uniformly spaced quantiles for deterministic results
    let mut total = 0.0;
    for i in 0..count {
        let u = (i as f64 + 0.5) / count as f64; // midpoint quantile
                                                 // Inverse CDF for power law: m = m_min * (1 - u)^(-1/(β-1))
                                                 // For β > 1, the CDF is: F(m) = 1 - (m/m_min)^(-(β-1))
                                                 // Inverse: m = m_min * (1 - u)^(-1/(β-1))
        let m_min = total_kg / count as f64 * 0.1; // smallest fragment is 10% of average
        let m = m_min * (1.0 - u as f64).powf(-1.0 / (beta - 1.0));
        masses.push(m);
        total += m;
    }

    // Normalize to total mass
    if total > 0.0 {
        let scale = total_kg / total;
        for m in &mut masses {
            *m *= scale;
        }
    }

    masses
}

/// Evaluate refined crew injury with fragment distribution and body region detail.
///
/// This is an UPGRADED version of [`evaluate_crew`] with more granular fragment
/// mass distribution and body region hit modelling.
///
/// # Arguments
/// * `protection_level` — Crew protection (None/Light/SpallLiner/Heavy).
/// * `residual_velocity_ms` — Projectile velocity after penetrating armour (m/s).
/// * `spall_fragments` — Number of BAD fragments (from PenetrationResult).
/// * `bad_spray_angle_deg` — Spray cone half-angle (degrees).
/// * `bad_total_mass_g` — Total mass of all BAD fragments (grams).
/// * `projectile_type` — "ball", "ap", "apfsds", etc.
/// * `num_crew` — Number of crew members in this position (1–3).
pub fn evaluate_crew_refined(
    protection_level: CrewProtection,
    residual_velocity_ms: f64,
    spall_fragments: i32,
    bad_spray_angle_deg: f64,
    bad_total_mass_g: f64,
    projectile_type: &str,
    num_crew: i32,
) -> CrewInjuryResult {
    let protection = spall_protection_factor(protection_level);
    let is_apfsds = matches!(projectile_type.to_lowercase().as_str(), "apfsds");

    if spall_fragments <= 0 || bad_total_mass_g <= 0.0 || residual_velocity_ms < 50.0 {
        let empty_regions: Vec<BodyRegionInjury> = BodyRegion::ALL
            .iter()
            .map(|&region| BodyRegionInjury {
                region,
                fragment_impacts: 0,
                fatal_hits: 0,
                serious_hits: 0,
                minor_hits: 0,
            })
            .collect();
        return CrewInjuryResult {
            total_impacts: 0,
            fatal_wounds: 0,
            serious_wounds: 0,
            minor_wounds: 0,
            crew_incapacitated: 0,
            region_breakdown: empty_regions,
            fatal_hit_probability: 0.0,
        };
    }

    // Generate fragment mass distribution
    let masses = generate_fragment_masses(bad_total_mass_g, spall_fragments, is_apfsds);
    let num_fragments = masses.len() as i32;

    // Fragment velocity (reduced by spray angle)
    let vel_factor = (bad_spray_angle_deg.max(5.0) / 45.0).clamp(0.2, 1.0);
    let frag_vel = (residual_velocity_ms * vel_factor).max(100.0);

    let regions = [
        BodyRegion::HeadNeck,
        BodyRegion::Thorax,
        BodyRegion::Abdomen,
        BodyRegion::Arms,
        BodyRegion::Legs,
    ];

    // Distribute fragments across body regions by area fraction.
    // Earlier regions (head/thorax) get first pick of the mass distribution
    // (worst-case: the largest fragments hit the most vital areas).
    let mut next_idx = 0;
    let mut region_injuries: Vec<BodyRegionInjury> = regions
        .iter()
        .map(|&region| {
            let area_frac = region_area_fraction(region);
            let hits_in_region =
                ((num_fragments as f64 * area_frac).round() as i32).min(num_fragments - next_idx);

            let mut fatal = 0;
            let mut serious = 0;
            let mut minor = 0;

            for j in next_idx..(next_idx + hits_in_region).min(num_fragments) {
                let mass_kg = masses[j as usize];
                let frag_ke_j = 0.5 * mass_kg * frag_vel.powi(2) / protection;
                let (fp, sp, mip) = region_lethality(region, frag_ke_j);

                if fp > 0.5 {
                    fatal += 1;
                } else if sp > 0.5 {
                    serious += 1;
                } else if mip > 0.5 {
                    minor += 1;
                }
            }
            next_idx += hits_in_region;

            BodyRegionInjury {
                region,
                fragment_impacts: hits_in_region.max(0),
                fatal_hits: fatal,
                serious_hits: serious,
                minor_hits: minor,
            }
        })
        .collect();

    // Remaining fragments (rounding loss) go to legs (largest area)
    let remaining = num_fragments - next_idx;
    if remaining > 0 {
        if let Some(legs) = region_injuries.last_mut() {
            for j in next_idx..num_fragments {
                let mass_kg = masses[j as usize];
                let frag_ke_j = 0.5 * mass_kg * frag_vel.powi(2) / protection;
                let (fp, sp, mip) = region_lethality(BodyRegion::Legs, frag_ke_j);
                if fp > 0.5 {
                    legs.fatal_hits += 1;
                } else if sp > 0.5 {
                    legs.serious_hits += 1;
                } else if mip > 0.5 {
                    legs.minor_hits += 1;
                }
                legs.fragment_impacts += 1;
            }
        }
    }

    // Sum totals
    let total_fatal: i32 = region_injuries.iter().map(|r| r.fatal_hits).sum();
    let total_serious: i32 = region_injuries.iter().map(|r| r.serious_hits).sum();
    let total_minor: i32 = region_injuries.iter().map(|r| r.minor_hits).sum();

    // Fatal hit probability: any fatal hit is very serious
    let fatal_prob = if total_fatal > 0 { 0.95 } else { 0.0 };

    // Crew incapacitation: count crew affected by fatal/serious wounds
    let wounded = total_fatal + total_serious + total_minor.min(total_minor);
    let incapacitated = wounded.min(num_crew).max(0);

    CrewInjuryResult {
        total_impacts: num_fragments,
        fatal_wounds: total_fatal,
        serious_wounds: total_serious,
        minor_wounds: total_minor,
        crew_incapacitated: incapacitated,
        region_breakdown: region_injuries,
        fatal_hit_probability: fatal_prob,
    }
}

// ── Deterministic random (threshold) helper ───────────────────────────────────

/// Returns `true` when probability `p` exceeds 0.5.
///
/// This is a **deterministic** threshold: probabilities above 0.5 always
/// trigger, those below never do.  Unit tests with clear energy margins
/// are therefore stable and repeatable.
///
/// A game integration should replace this with a seeded PRNG
/// (e.g. oorandom) seeded once at mission start.  The 0.5 split provides
/// a useful default: moderate threats (p ≈ 0.3–0.7) are decided by the
/// caller's energy-threshold logic rather than by randomness, while
/// high-confidence events (p > 0.5) always fire.
fn rand_threshold(p: f64) -> bool {
    // ponytail: deterministic 0.5 split, not a true RNG.  Replace with
    // a seeded PRNG if gameplay-acceptable randomness is needed.
    p > 0.5
}

// ── Fire propagation types ─────────────────────────────────────────────────────

/// Vehicle-level fire suppression capability.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum FireSuppression {
    /// No suppression — fire spreads freely
    None,
    /// Hand extinguishers only
    Manual,
    /// Automatic fire suppression system (AFSS)
    Automatic,
    /// Halon gas flood (military AFV systems)
    Halon,
    /// Armoured/suppressed — fire is contained within compartment
    Armoured,
}

/// Status of a fire in a vehicle component.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum FireStatus {
    NoFire,
    /// Low-intensity, may self-extinguish
    Smoldering,
    /// Active fire, can spread
    Burning,
    /// Maximum intensity, rapid spread
    FullyEngulfed,
}

/// Component fire state for propagation evaluation.
#[derive(Debug, Clone)]
pub struct ComponentFireState {
    pub component_index: usize,
    pub fire_status: FireStatus,
    /// 0.0–1.0
    pub fire_intensity: f64,
}

/// Result of fire propagation evaluation.
#[derive(Debug, Clone)]
pub struct FirePropagationResult {
    /// Per-component fire status after propagation.
    pub component_fires: Vec<ComponentFireState>,
    /// Overall probability that vehicle is fully involved (>50% components burning).
    pub vehicle_fully_involved_probability: f64,
    /// Estimated time to vehicle destruction in seconds (if fire is unchecked).
    pub estimated_destruction_time_s: f64,
}

/// Evaluate fire propagation across vehicle components.
///
/// Starts from a set of damaged components (those with `fire_started = true`)
/// and models the spread to adjacent components over time.
///
/// # Arguments
/// * `fire_states` — Current fire state for each vehicle component.
/// * `component_configs` — Component configuration (used for adjacency/proximity).
/// * `suppression` — Vehicle-level fire suppression capability.
/// * `time_step_s` — Time increment for propagation (seconds).
/// * `compartment_sealed` — Whether components are in sealed compartments.
///
/// # Returns
/// Updated fire states for all components after propagation.
pub fn evaluate_fire_propagation(
    fire_states: &[ComponentFireState],
    component_configs: &[ComponentConfig],
    suppression: FireSuppression,
    time_step_s: f64,
    compartment_sealed: bool,
) -> FirePropagationResult {
    let n = fire_states.len();
    let mut new_states = fire_states.to_vec();

    // Suppression modifier: reduces spread probability
    let suppression_factor: f64 = match suppression {
        FireSuppression::None => 1.0,
        FireSuppression::Manual => 0.7,
        FireSuppression::Automatic => 0.35,
        FireSuppression::Halon => 0.15,
        FireSuppression::Armoured => 0.05,
    };

    // Compartment sealed: reduces oxygen flow → slower spread
    let oxygen_factor = if compartment_sealed { 0.6 } else { 1.0 };

    for i in 0..n {
        // Only spreading components can propagate
        if new_states[i].fire_status != FireStatus::FullyEngulfed
            && new_states[i].fire_status != FireStatus::Burning
        {
            continue;
        }

        let source_intensity = new_states[i].fire_intensity;

        // Check all other components for potential ignition
        for j in 0..n {
            if i == j {
                continue;
            }
            if new_states[j].fire_status != FireStatus::NoFire
                && new_states[j].fire_status != FireStatus::Smoldering
            {
                continue;
            }

            // Proximity: assume distance between i and j based on index order
            // (adjacent indices = closer, indices far apart = farther)
            let dist_factor = 1.0 / (1.0 + (i as f64 - j as f64).abs() * 0.5);

            // Fuel load of target (derived from component type)
            let target_fuel_load = match component_configs.get(j) {
                Some(cfg) => match cfg.component {
                    ComponentType::FuelTank { .. } => 0.9,
                    ComponentType::AmmoRack { .. } => 0.8,
                    ComponentType::Engine { .. } => 0.5,
                    ComponentType::Crew { .. } => 0.3,
                    ComponentType::Transmission => 0.2,
                },
                None => 0.1,
            };

            // Base spread probability per second
            let base_spread = source_intensity * dist_factor * target_fuel_load * 0.25;

            // Apply suppression and oxygen
            let spread_prob =
                (base_spread * suppression_factor * oxygen_factor * time_step_s).clamp(0.0, 0.99);

            // Deterministic threshold as per project convention
            if spread_prob > 0.5 {
                // Ignite the target
                let target_is_fuel = matches!(
                    component_configs.get(j).map(|c| &c.component),
                    Some(ComponentType::FuelTank { .. })
                );

                new_states[j] = ComponentFireState {
                    component_index: j,
                    fire_status: if target_is_fuel {
                        FireStatus::FullyEngulfed
                    } else {
                        FireStatus::Burning
                    },
                    fire_intensity: if target_is_fuel { 0.9 } else { 0.5 },
                };
            }
        }

        // Intensify the source fire over time (if burning → fully engulfed)
        if new_states[i].fire_status == FireStatus::Burning {
            new_states[i].fire_intensity =
                (new_states[i].fire_intensity + 0.1 * time_step_s).min(1.0);
            if new_states[i].fire_intensity >= 0.8 {
                new_states[i].fire_status = FireStatus::FullyEngulfed;
            }
        }
    }

    // Count fire involvement
    let burning_count = new_states
        .iter()
        .filter(|s| {
            matches!(
                s.fire_status,
                FireStatus::Burning | FireStatus::FullyEngulfed
            )
        })
        .count() as f64;
    let fully_involved = burning_count / n.max(1) as f64 > 0.5;

    // Estimated destruction time (if most components are burning)
    let destruction_time = if burning_count > 0.0 {
        let involvement = burning_count / n.max(1) as f64;
        let base_time = 60.0 * suppression_factor; // 60s with no suppression
        let sealed_penalty = if compartment_sealed { 1.5 } else { 1.0 };
        base_time * sealed_penalty / involvement.max(0.1)
    } else {
        f64::INFINITY
    };

    FirePropagationResult {
        component_fires: new_states,
        vehicle_fully_involved_probability: if fully_involved { 0.8 } else { 0.0 },
        estimated_destruction_time_s: destruction_time,
    }
}

/// Convert a ComponentDamageResult to initial fire state.
pub fn damage_to_fire_state(
    damage: &ComponentDamageResult,
    component_index: usize,
) -> ComponentFireState {
    if damage.explosion {
        ComponentFireState {
            component_index,
            fire_status: FireStatus::FullyEngulfed,
            fire_intensity: 1.0,
        }
    } else if damage.fire_started {
        ComponentFireState {
            component_index,
            fire_status: FireStatus::Burning,
            fire_intensity: 0.4,
        }
    } else {
        ComponentFireState {
            component_index,
            fire_status: FireStatus::NoFire,
            fire_intensity: 0.0,
        }
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Helpers ─────────────────────────────────────────────────────────────────

    /// Create a default component config for a given component type with
    /// the local armour parameters zeroed (unarmoured stowage).
    fn cfg(c: ComponentType) -> ComponentConfig {
        ComponentConfig {
            component: c,
            local_armor_thickness_mm: 0.0,
            local_armor_material: "steel_structural",
            local_angle_deg: 0.0,
        }
    }

    /// Quick damage evaluation with just the essential fields.
    fn eval(
        c: &ComponentConfig,
        res_vel: f64,
        mass_g: f64,
        proj_type: &str,
    ) -> ComponentDamageResult {
        evaluate_component_damage(c, res_vel, mass_g, proj_type, 7.62, 0, 0.0, 0.0)
    }

    /// Evaluate with BAD fragment data.
    fn eval_bad(
        c: &ComponentConfig,
        res_vel: f64,
        mass_g: f64,
        proj_type: &str,
        cal_mm: f64,
        spall: i32,
        spray_deg: f64,
        bad_mass_g: f64,
    ) -> ComponentDamageResult {
        evaluate_component_damage(
            c, res_vel, mass_g, proj_type, cal_mm, spall, spray_deg, bad_mass_g,
        )
    }

    // ── Ammo rack tests ─────────────────────────────────────────────────────────

    #[test]
    fn ammo_rack_small_arms_threshold_just_below() {
        // 4g projectile at 50 m/s → 0.5 * 0.004 * 50^2 = 5 J → below 5 kJ threshold
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::SmallArms,
        });
        let r = eval(&c, 50.0, 4.0, "ball");
        assert!(!r.explosion, "no cookoff below threshold");
        // At 5J vs 5000J threshold, energy is far below
        // ponytail: residual_ke_j = 5J, threshold = 5000J → energy_ratio clips to 0
    }

    #[test]
    fn ammo_rack_small_arms_cookoff_at_threshold() {
        // Large calibre at high residual velocity: 42.8g .50 BMG at 500 m/s →
        // 0.5 * 0.0428 * 500^2 = 5350 J → just above 5 kJ threshold
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::SmallArms,
        });
        // Use a high residual velocity to clearly exceed threshold
        let r = eval(&c, 800.0, 42.8, "ap");
        // At 0.5 * 0.0428 * 800^2 = 13,696 J >> 5000 J → cookoff likely
        assert!(
            r.component_destroyed || r.fire_started,
            "significant residual energy above small-arms threshold should cause cookoff or fire"
        );
    }

    #[test]
    fn ammo_rack_heat_sensitive_cookoff() {
        // HEAT ammo threshold is 1 kJ, sensitivity = 2.0.
        // Need cookoff_prob > 0.5 → energy_ratio > 1.347.
        // 9.5 g at 600 m/s → 0.5 * 0.0095 * 600^2 = 1710 J → ratio 1.71
        // cookoff_prob = 1 - exp(-2.0 * 0.71) = 0.760 > 0.5 ✓
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::HEAT,
        });
        let r = eval(&c, 600.0, 9.5, "ap");
        assert!(
            r.component_destroyed || r.explosion,
            "HEAT ammo should cookoff above 1 kJ threshold at 1710 J residual"
        );
    }

    #[test]
    fn ammo_rack_low_energy_no_damage() {
        // 4 g at 25 m/s → 1.25 J, far below any threshold
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::CannonShells,
        });
        let r = eval(&c, 25.0, 4.0, "ball");
        assert!(!r.explosion);
        assert!(!r.fire_started);
        assert!(!r.component_destroyed);
    }

    #[test]
    fn ammo_rack_incendiary_increases_fire_chance() {
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::SmallArms,
        });
        // 4 g at 600 m/s → 720 J — below 5 kJ threshold, but incendiary
        // rounds have higher fire multiplier (3.0)
        // fire_prob = 0.05 * 3.0 * 1.0 * 0.0 (energy_ratio < 1.0 so clamped to 0)
        // Actually below threshold so fire_prob path isn't reached.
        // Just ensuring it runs without panic.
        let r = eval(&c, 600.0, 4.0, "incendiary");
        assert!(r.residual_energy_j >= 0.0);
    }

    // ── Fuel tank tests ─────────────────────────────────────────────────────────

    #[test]
    fn fuel_tank_petrol_ignites_easier_than_diesel() {
        // Same conditions for both fuel types at moderate energy
        let c_pet = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Petrol,
        });
        let c_die = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Diesel,
        });
        // 9.5 g at 600 m/s → 1710 J → above leak threshold (200 J)
        // Both tanks are perforated → leaking → disabled.
        let r_pet = eval(&c_pet, 600.0, 9.5, "ball");
        let r_die = eval(&c_die, 600.0, 9.5, "ball");
        // Perforated fuel tank always leaks → component_disabled.
        assert!(
            r_pet.component_disabled,
            "petrol tank should leak when perforated"
        );
        assert!(
            r_die.component_disabled,
            "diesel tank should leak when perforated"
        );
        // Petrol has higher fire probability than diesel.  At deterministic
        // threshold (p > 0.5), both fire_probs are below 0.5 at this energy.
        assert!(
            !r_pet.explosion,
            "petrol vapour explosion unlikely at 1710 J"
        );
        assert!(
            !r_die.explosion,
            "diesel vapour explosion unlikely at 1710 J"
        );
    }

    #[test]
    fn fuel_tank_below_leak_threshold() {
        // 4 g at 50 m/s → 5 J < 200 J threshold
        let c = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Diesel,
        });
        let r = eval(&c, 50.0, 4.0, "ball");
        assert!(!r.explosion);
        assert!(!r.fire_started);
        assert!(!r.component_disabled);
    }

    #[test]
    fn fuel_tank_explosion_high_energy() {
        // 42.8 g .50 BMG at 800 m/s → 13,696 J → well above diesel
        // explosion threshold of 8 kJ
        let c = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Diesel,
        });
        let r = eval(&c, 800.0, 42.8, "api");
        assert!(
            r.explosion || r.fire_started,
            "high energy into fuel tank should cause explosion or fire"
        );
    }

    // ── Engine tests ────────────────────────────────────────────────────────────

    #[test]
    fn engine_low_energy_minor_damage() {
        // 4 g at 200 m/s → 80 J → very low relative to engine mass
        let c = cfg(ComponentType::Engine {
            engine_type: EngineType::Diesel,
        });
        let r = eval(&c, 200.0, 4.0, "ball");
        assert!(!r.component_destroyed);
        assert!(!r.component_disabled);
        // Mobility loss should be small (< 0.15 absorbed fraction → < 7.5%)
        assert!(r.mobility_loss_fraction < 0.10);
    }

    #[test]
    fn engine_full_kill_high_energy() {
        // Large calibre at high velocity:
        // 42.8 g at 900 m/s → 17,334 J into 800 kg diesel block
        // absorbed fraction = 17334 / (800*150) = 0.144 → minor damage?
        // Hmm, need more energy. Try 42.8g at 1500 m/s → 48,150 J
        // absorbed = 48150 / 120000 = 0.40 → disabled
        let c = cfg(ComponentType::Engine {
            engine_type: EngineType::Diesel,
        });
        let r = eval(&c, 1500.0, 42.8, "ap");
        assert!(
            r.component_disabled || r.mobility_loss_fraction > 0.3,
            "high energy into diesel engine should cause major damage"
        );
    }

    #[test]
    fn engine_petrol_lighter_block_more_damage() {
        // 9.5 g at 800 m/s → 3040 J
        // Petrol block: 200 kg, max absorb = 30,000 J
        // absorbed fraction = 3040 / 30000 = 0.101 → minor
        // Diesel block: 800 kg, max absorb = 120,000 J
        // absorbed fraction = 3040 / 120000 = 0.025 → trivial
        let c_pet = cfg(ComponentType::Engine {
            engine_type: EngineType::Petrol,
        });
        let c_die = cfg(ComponentType::Engine {
            engine_type: EngineType::Diesel,
        });
        let r_pet = eval(&c_pet, 800.0, 9.5, "ball");
        let r_die = eval(&c_die, 800.0, 9.5, "ball");
        assert!(
            r_pet.mobility_loss_fraction >= r_die.mobility_loss_fraction,
            "petrol engine (lighter) should lose more mobility than diesel (heavier)"
        );
    }

    #[test]
    fn engine_incendiary_fire() {
        // 9.5 g at 900 m/s → 3847 J
        // Petrol engine: 200 kg, absorbed fraction = 3847 / 30000 = 0.128
        // Below 0.20 fire threshold, but incendiary multiplier = 3.0
        // fire_prob = 0.05 * 0.128 * 10 * 3.0 = 0.192 → possible
        let c = cfg(ComponentType::Engine {
            engine_type: EngineType::Petrol,
        });
        let r = eval(&c, 900.0, 9.5, "incendiary");
        // Just verify it runs and gives sensible results
        assert!(r.secondary_fragments >= 0);
    }

    // ── Transmission tests ──────────────────────────────────────────────────────

    #[test]
    fn transmission_minor_damage() {
        let c = cfg(ComponentType::Transmission);
        let r = eval(&c, 200.0, 4.0, "ball");
        assert!(!r.component_destroyed);
        assert!(!r.component_disabled);
    }

    #[test]
    fn transmission_severe_damage() {
        // 42.8 g at 1500 m/s → 48,150 J; max absorb = 60,000 J;
        // absorbed fraction = 0.80 → destroyed
        let c = cfg(ComponentType::Transmission);
        let r = eval(&c, 1500.0, 42.8, "ap");
        assert!(
            r.mobility_loss_fraction > 0.5,
            "high energy into transmission should cause heavy mobility loss"
        );
    }

    // ── Crew injury tests ───────────────────────────────────────────────────────

    #[test]
    fn crew_no_spall_no_casualty() {
        // No BAD fragments → no crew casualties at low energy
        let c = cfg(ComponentType::Crew {
            protection_level: CrewProtection::None,
        });
        let r = eval(&c, 50.0, 4.0, "ball");
        assert_eq!(r.crew_casualties, 0);
    }

    #[test]
    fn crew_spall_causes_casualty() {
        // Moderate BAD load: 50 fragments, 45° spray, 50g total mass, 200 m/s
        // avg_frag_mass = 50g / 50 = 1g = 0.001 kg
        // vel_factor = (45/45).clamp(0.2, 1.0) = 1.0
        // 100.0 / 200.0.max(100.0) = 0.5 → max(1.0, 0.5) = 1.0
        // frag_vel = 200 * 1.0 = 200 m/s
        // frag_ke = 0.5 * 0.001 * 200^2 = 20 J → below 80 J threshold,
        // and below 40 J (half threshold) → 0 casualties
        let c = cfg(ComponentType::Crew {
            protection_level: CrewProtection::None,
        });
        let r = eval_bad(&c, 200.0, 9.5, "ball", 7.62, 50, 45.0, 50.0);
        assert_eq!(
            r.crew_casualties, 0,
            "low-energy BAD fragments should not cause casualties"
        );
    }

    #[test]
    fn crew_heavy_spall_causes_casualty() {
        // Heavier fragments: 600g total, 10 fragments, 800 m/s, 15° spray
        // avg_frag_mass = 60g = 0.06 kg
        // vel_factor = 15/45 = 0.333, frag_vel = 800 * 0.333 = 266.4 m/s
        // frag_ke = 0.5 * 0.06 * 266.4^2 = 2,129 J → >> 80 J
        let c = cfg(ComponentType::Crew {
            protection_level: CrewProtection::None,
        });
        let r = eval_bad(&c, 800.0, 9.5, "ball", 7.62, 10, 15.0, 600.0);
        assert!(
            r.crew_casualties >= 1,
            "heavy BAD fragments should cause crew casualties"
        );
    }

    #[test]
    fn crew_spall_liner_reduces_casualties() {
        // Same heavy BAD load with spall liner
        // Protection factor: SpallLiner = 5.0 → effective frag KE = 2129/5 = 426 J
        // Still above 80 J threshold → casualties expected
        let c_none = cfg(ComponentType::Crew {
            protection_level: CrewProtection::None,
        });
        let c_liner = cfg(ComponentType::Crew {
            protection_level: CrewProtection::SpallLiner,
        });
        let r_none = eval_bad(&c_none, 800.0, 9.5, "ball", 7.62, 10, 15.0, 600.0);
        let r_liner = eval_bad(&c_liner, 800.0, 9.5, "ball", 7.62, 10, 15.0, 600.0);
        // Spall liner should reduce casualties (fewer fragments above threshold)
        assert!(
            r_liner.crew_casualties <= r_none.crew_casualties,
            "spall liner should not increase casualties"
        );
    }

    #[test]
    fn crew_heavy_protection_no_casualties() {
        // Heavy protection (factor 10) against moderate BAD
        // 20 fragments, 30° spray, 100g total, 500 m/s
        // avg_frag_mass = 5g = 0.005 kg; vel_factor = 30/45 = 0.667
        // frag_vel = 500 * 0.667 * 0.2 = 66.7; frag_ke = 0.5 * 0.005 * 66.7^2 / 10 = 1.1 J
        // Well below 80 J → 0 casualties
        let c = cfg(ComponentType::Crew {
            protection_level: CrewProtection::Heavy,
        });
        let r = eval_bad(&c, 500.0, 9.5, "ball", 7.62, 20, 30.0, 100.0);
        assert_eq!(
            r.crew_casualties, 0,
            "heavy protection should prevent casualties"
        );
    }

    // ── Edge-case / integration tests ───────────────────────────────────────────

    #[test]
    fn zero_velocity_no_damage() {
        let types = [
            ComponentType::AmmoRack {
                ammo_type: AmmoStoredType::SmallArms,
            },
            ComponentType::FuelTank {
                fuel_type: FuelType::Diesel,
            },
            ComponentType::Engine {
                engine_type: EngineType::Diesel,
            },
            ComponentType::Transmission,
            ComponentType::Crew {
                protection_level: CrewProtection::None,
            },
        ];
        for ct in &types {
            let c = cfg(*ct);
            let r = eval(&c, 0.0, 4.0, "ball");
            assert!(!r.explosion, "{:?}: no explosion at zero velocity", ct);
            assert!(!r.fire_started, "{:?}: no fire at zero velocity", ct);
            assert!(
                !r.component_destroyed,
                "{:?}: no destruction at zero velocity",
                ct
            );
        }
    }

    #[test]
    fn residual_energy_never_negative() {
        let c = cfg(ComponentType::Engine {
            engine_type: EngineType::Diesel,
        });
        let r = eval(&c, 9999.0, 1000.0, "ap");
        assert!(
            r.residual_energy_j >= 0.0,
            "residual energy should never be negative (got {})",
            r.residual_energy_j
        );
    }

    #[test]
    fn ammo_rack_mixed_type_uses_lowest_threshold() {
        // Mixed ammo uses the lowest threshold (1 kJ, sensitivity 1.2).
        // Need cookoff_prob > 0.5 → energy_ratio > 1.578.
        // 9.5 g at 650 m/s → 0.5 * 0.0095 * 650^2 = 2007 J → ratio 2.007
        // cookoff_prob = 1 - exp(-1.2 * 1.007) = 0.702 > 0.5 ✓
        let c = cfg(ComponentType::AmmoRack {
            ammo_type: AmmoStoredType::Mixed,
        });
        let r = eval(&c, 650.0, 9.5, "ball");
        assert!(
            r.component_destroyed || r.explosion,
            "Mixed ammo rack (1 kJ threshold) should cookoff at 2007 J residual"
        );
    }

    #[test]
    fn jp8_intermediate_ignition() {
        // JP8 should be harder to ignite than petrol but easier than diesel
        let c_jp8 = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::JP8,
        });
        let c_pet = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Petrol,
        });
        let c_die = cfg(ComponentType::FuelTank {
            fuel_type: FuelType::Diesel,
        });

        // Same conditions: 9.5g at 700 m/s → 2327 J, all >> 200 J threshold
        let r_jp8 = eval(&c_jp8, 700.0, 9.5, "ball");
        let r_pet = eval(&c_pet, 700.0, 9.5, "ball");
        let r_die = eval(&c_die, 700.0, 9.5, "ball");

        // All tanks leak when perforated → component_disabled is true.
        assert!(
            r_pet.component_disabled,
            "petrol tank should leak at 2327 J"
        );
        assert!(r_jp8.component_disabled, "JP8 tank should leak at 2327 J");
        assert!(
            r_die.component_disabled,
            "diesel tank should leak at 2327 J"
        );
        // Base fire probs at 2327 J (all < 0.5):
        //   Petrol:  0.08 * 2.327 = 0.186 → no fire
        //   JP8:     0.04 * 2.327 = 0.093 → no fire
        //   Diesel:  0.02 * 2.327 = 0.047 → no fire
        assert!(
            !r_pet.fire_started,
            "petrol needs >~6250 J for fire at deterministic threshold"
        );
        assert!(!r_jp8.fire_started, "JP8 needs >~12500 J for fire");
        assert!(!r_die.fire_started, "diesel needs >~25000 J for fire");
    }

    // ── Fire propagation tests ──────────────────────────────────────────────────

    #[test]
    fn fire_propagation_no_initial_fire() {
        let states = vec![
            ComponentFireState {
                component_index: 0,
                fire_status: FireStatus::NoFire,
                fire_intensity: 0.0,
            },
            ComponentFireState {
                component_index: 1,
                fire_status: FireStatus::NoFire,
                fire_intensity: 0.0,
            },
        ];
        let cfgs = vec![
            cfg(ComponentType::FuelTank {
                fuel_type: FuelType::Diesel,
            }),
            cfg(ComponentType::Engine {
                engine_type: EngineType::Diesel,
            }),
        ];
        let r = evaluate_fire_propagation(&states, &cfgs, FireSuppression::None, 1.0, false);
        assert!(r
            .component_fires
            .iter()
            .all(|s| s.fire_status == FireStatus::NoFire));
    }

    #[test]
    fn fire_propagation_spreads_from_burning_component() {
        // Fuel tank fully engulfed should spread to adjacent engine
        let states = vec![
            ComponentFireState {
                component_index: 0,
                fire_status: FireStatus::FullyEngulfed,
                fire_intensity: 1.0,
            },
            ComponentFireState {
                component_index: 1,
                fire_status: FireStatus::NoFire,
                fire_intensity: 0.0,
            },
        ];
        let cfgs = vec![
            cfg(ComponentType::FuelTank {
                fuel_type: FuelType::Petrol,
            }),
            cfg(ComponentType::Engine {
                engine_type: EngineType::Petrol,
            }),
        ];
        let r = evaluate_fire_propagation(&states, &cfgs, FireSuppression::None, 7.0, false);
        // Engine should have ignited (adjacent to burning fuel tank)
        assert!(
            r.component_fires[1].fire_status != FireStatus::NoFire,
            "fire should spread from fuel tank to engine"
        );
    }

    #[test]
    fn fire_suppression_reduces_spread() {
        let states = vec![
            ComponentFireState {
                component_index: 0,
                fire_status: FireStatus::FullyEngulfed,
                fire_intensity: 1.0,
            },
            ComponentFireState {
                component_index: 1,
                fire_status: FireStatus::NoFire,
                fire_intensity: 0.0,
            },
        ];
        let cfgs = vec![
            cfg(ComponentType::FuelTank {
                fuel_type: FuelType::Petrol,
            }),
            cfg(ComponentType::Engine {
                engine_type: EngineType::Petrol,
            }),
        ];
        let r_none = evaluate_fire_propagation(&states, &cfgs, FireSuppression::None, 1.0, false);
        let r_halon = evaluate_fire_propagation(&states, &cfgs, FireSuppression::Halon, 1.0, false);
        // With no suppression, fire spreads more
        let spread_none = r_none
            .component_fires
            .iter()
            .filter(|s| {
                matches!(
                    s.fire_status,
                    FireStatus::Burning | FireStatus::FullyEngulfed
                )
            })
            .count();
        let spread_halon = r_halon
            .component_fires
            .iter()
            .filter(|s| {
                matches!(
                    s.fire_status,
                    FireStatus::Burning | FireStatus::FullyEngulfed
                )
            })
            .count();
        assert!(
            spread_halon <= spread_none,
            "halon should not increase fire spread"
        );
    }

    #[test]
    fn sealed_compartment_slows_fire() {
        let states = vec![
            ComponentFireState {
                component_index: 0,
                fire_status: FireStatus::FullyEngulfed,
                fire_intensity: 1.0,
            },
            ComponentFireState {
                component_index: 1,
                fire_status: FireStatus::NoFire,
                fire_intensity: 0.0,
            },
        ];
        let cfgs = vec![
            cfg(ComponentType::FuelTank {
                fuel_type: FuelType::Petrol,
            }),
            cfg(ComponentType::Engine {
                engine_type: EngineType::Petrol,
            }),
        ];
        let r_open = evaluate_fire_propagation(&states, &cfgs, FireSuppression::None, 1.0, false);
        let r_sealed = evaluate_fire_propagation(&states, &cfgs, FireSuppression::None, 1.0, true);
        let spread_open = r_open
            .component_fires
            .iter()
            .filter(|s| {
                matches!(
                    s.fire_status,
                    FireStatus::Burning | FireStatus::FullyEngulfed
                )
            })
            .count();
        let spread_sealed = r_sealed
            .component_fires
            .iter()
            .filter(|s| {
                matches!(
                    s.fire_status,
                    FireStatus::Burning | FireStatus::FullyEngulfed
                )
            })
            .count();
        assert!(
            spread_sealed <= spread_open,
            "sealed compartments should not increase spread"
        );
    }

    // ── Refined crew injury tests ──────────────────────────────────────────────

    #[test]
    fn crew_refined_no_spall_no_injury() {
        let r = evaluate_crew_refined(CrewProtection::None, 50.0, 0, 0.0, 0.0, "ball", 1);
        assert_eq!(r.total_impacts, 0);
        assert_eq!(r.fatal_wounds, 0);
        assert_eq!(r.crew_incapacitated, 0);
        assert_eq!(r.region_breakdown.len(), 5);
    }

    #[test]
    fn crew_refined_apfsds_high_spall() {
        // APFSDS produces fine, high-velocity fragments
        let r = evaluate_crew_refined(CrewProtection::None, 800.0, 200, 15.0, 100.0, "apfsds", 3);
        assert!(r.total_impacts > 0, "should produce fragment impacts");
        let has_casualties = r.crew_incapacitated > 0 || r.fatal_wounds > 0 || r.serious_wounds > 0;
        assert!(
            has_casualties,
            "high-velocity APFSDS should cause crew casualties"
        );
    }

    #[test]
    fn crew_refined_spall_liner_reduces_severity() {
        let r_none = evaluate_crew_refined(CrewProtection::None, 600.0, 50, 20.0, 200.0, "ball", 2);
        let r_liner = evaluate_crew_refined(
            CrewProtection::SpallLiner,
            600.0,
            50,
            20.0,
            200.0,
            "ball",
            2,
        );
        // Liner should not increase fatal wounds
        assert!(
            r_liner.fatal_wounds <= r_none.fatal_wounds,
            "spall liner should not increase fatal wounds (liner={} vs none={})",
            r_liner.fatal_wounds,
            r_none.fatal_wounds
        );
        // Total impact count is the same (same input fragments)
        assert_eq!(
            r_liner.total_impacts, r_none.total_impacts,
            "spall liner does not change fragment count"
        );
    }

    #[test]
    fn crew_refined_region_breakdown_sums() {
        let r = evaluate_crew_refined(CrewProtection::None, 700.0, 30, 10.0, 80.0, "ap", 2);
        let region_total: i32 = r
            .region_breakdown
            .iter()
            .map(|rb| rb.fragment_impacts)
            .sum();
        assert!(region_total > 0, "region breakdown should have fragments");
        assert!(
            region_total >= r.total_impacts || r.total_impacts == 0,
            "region fragment sum ({}) should cover total impacts ({})",
            region_total,
            r.total_impacts
        );
        // All 5 regions present
        assert_eq!(r.region_breakdown.len(), 5);
    }

    #[test]
    fn crew_refined_heavy_protection_prevents_fatal() {
        let r = evaluate_crew_refined(CrewProtection::Heavy, 500.0, 20, 25.0, 50.0, "ball", 1);
        // Heavy protection (factor 10) — few if any fatal wounds
        assert!(
            r.fatal_wounds <= 1,
            "heavy protection should prevent most fatal wounds (got {})",
            r.fatal_wounds
        );
    }

    #[test]
    fn fragment_mass_distribution_power_law() {
        let masses = generate_fragment_masses(100.0, 50, false);
        assert_eq!(masses.len(), 50);
        let total: f64 = masses.iter().sum();
        // Total should approximate 100 g = 0.1 kg
        assert!(
            (total - 0.1).abs() < 0.02,
            "total mass should be ~0.1 kg, got {}",
            total
        );
        // Power law means small fragments are abundant, large fragments are few.
        // First fragment (lowest quantile) should be the smallest, last the largest.
        assert!(
            masses[0] < masses[masses.len() - 1],
            "power law: first fragment ({:.6}) should be smaller than last ({:.6})",
            masses[0],
            masses[masses.len() - 1]
        );
    }

    #[test]
    fn fragment_mass_apfsds_finer_than_conventional() {
        let masses_conv = generate_fragment_masses(100.0, 50, false);
        let masses_apfsds = generate_fragment_masses(100.0, 50, true);
        // APFSDS (β=2.2) produces more uniform (finer) fragments than
        // conventional (β=1.8). The ratio of smallest to largest fragment
        // should be larger for APFSDS (closer to 1 = more uniform).
        let conv_ratio = masses_conv[0] / masses_conv[masses_conv.len() - 1];
        let apfsds_ratio = masses_apfsds[0] / masses_apfsds[masses_apfsds.len() - 1];
        assert!(
            apfsds_ratio > conv_ratio,
            "APFSDS should have more uniform fragment distribution (ratio {:.4} vs {:.4})",
            apfsds_ratio,
            conv_ratio
        );
    }

    #[test]
    fn region_lethality_ordering() {
        // Head/neck should always be more lethal than legs for the same KE
        let (fp_head, _, _) = region_lethality(BodyRegion::HeadNeck, 200.0);
        let (fp_legs, _, _) = region_lethality(BodyRegion::Legs, 200.0);
        assert!(
            fp_head > fp_legs,
            "head/neck lethality ({}) should exceed leg lethality ({})",
            fp_head,
            fp_legs
        );
    }
}
