services:
  abe-headless-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        STEAM_USERNAME: ${STEAM_USERNAME:-anonymous}
        STEAM_PASSWORD: ${STEAM_PASSWORD:-}
    container_name: abe-headless-test
    stdin_open: true
    tty: true
    # Mount source for iterative development without rebuild for all but Rust
    volumes:
      - ../addons:/abe/addons
      - ../data:/abe/data
      - ../.hemtt:/abe/.hemtt
      - ../.hemttout:/abe/.hemttout
