// ── Build-time PHF map generation ────────────────────────────────────────────
//
// Primary source: data/real_weapons.tsv + data/arma_weapon_map.tsv
// Legacy fallback: data/ir_weapons.tsv
// Also reads: data/ir_ammo.tsv, data/ir_armor.tsv, data/ir_clothing.tsv, data/ir_materials.tsv

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("generated_irl.rs");

    // Trigger rebuild if ANY TSV file changes
    println!("cargo:rerun-if-changed=../data/real_weapons.tsv");
    println!("cargo:rerun-if-changed=../data/arma_weapon_map.tsv");
    println!("cargo:rerun-if-changed=../data/ir_weapons.tsv");
    println!("cargo:rerun-if-changed=../data/ir_ammo.tsv");
    println!("cargo:rerun-if-changed=../data/ir_armor.tsv");
    println!("cargo:rerun-if-changed=../data/ir_clothing.tsv");
    println!("cargo:rerun-if-changed=../data/ir_materials.tsv");

    let real_weapons_tsv =
        fs::read_to_string("../data/real_weapons.tsv").unwrap_or_else(|_| String::new());
    let arma_weapon_map_tsv =
        fs::read_to_string("../data/arma_weapon_map.tsv").unwrap_or_else(|_| String::new());
    let weapons_tsv =
        fs::read_to_string("../data/ir_weapons.tsv").unwrap_or_else(|_| String::new());
    let ammo_tsv = fs::read_to_string("../data/ir_ammo.tsv").unwrap_or_else(|_| String::new());
    let armor_tsv = fs::read_to_string("../data/ir_armor.tsv").unwrap_or_else(|_| String::new());
    let materials_tsv =
        fs::read_to_string("../data/ir_materials.tsv").unwrap_or_else(|_| String::new());

    let mut output = String::new();
    output.push_str("// auto-generated by build.rs — do not edit\n");
    output.push_str(
        "// source: data/real_weapons.tsv + arma_weapon_map.tsv + legacy ir_weapons.tsv\n\n",
    );

    output.push_str("use phf::phf_map;\n\n");
    output.push_str("use crate::systems::ir_lookup::{WeaponParams, AmmoParams};\n\n");

    // ── Helper: parse f64 from TSV field ──
    let fmt_f64 = |s: &str| -> String {
        let v: f64 = s.parse().unwrap_or(0.0);
        if v == v.floor() && v.is_finite() {
            format!("{}.0", v)
        } else {
            format!("{}", v)
        }
    };

    // ── Load real_weapons.tsv (canonical IRL spec source) ──
    //   Columns: weapon_id, manufacturer, model, variant, cartridge,
    //            caliber_mm, barrel_mm, twist_mm, twist_dir, pressure_mpa,
    //            projectile_mass_g, muzzle_velocity_ms, source, confidence
    let mut real_weapon_specs: HashMap<String, String> = HashMap::new();
    for line in real_weapons_tsv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 14 {
            continue;
        }
        let wid = fields[0].trim();
        if wid.is_empty() || wid == "weapon_id" {
            continue;
        }
        // Skip entries with zero specs (not yet researched)
        let cal: f64 = fields[5].parse().unwrap_or(0.0);
        let barrel: f64 = fields[6].parse().unwrap_or(0.0);
        if cal <= 0.0 || barrel <= 0.0 {
            continue;
        }
        let twist: f64 = fields[7].parse().unwrap_or(0.0);
        let pressure: f64 = fields[9].parse().unwrap_or(0.0);
        let mass: f64 = fields[10].parse().unwrap_or(0.0);
        let key = wid.replace('\\', "\\\\").replace('\'', "\\'");
        // Store WeaponParams body WITHOUT the key prefix — the key is
        // prepended during output so that arma_map mappings (which can map
        // different arma_keys to the same weapon_id) produce the correct key.
        real_weapon_specs.insert(
            key.clone(),
            format!(
                "barrel_length_mm: {},\n\
                 chamber_pressure_mpa: {},\n\
                 caliber_mm: {},\n\
                 projectile_mass_g: {},\n\
                 barrel_twist_mm: {},\n",
                fmt_f64(&barrel.to_string()),
                fmt_f64(&pressure.to_string()),
                fmt_f64(&cal.to_string()),
                fmt_f64(&mass.to_string()),
                fmt_f64(&twist.to_string()),
            ),
        );
    }

    // ── Load arma_weapon_map.tsv (Arma classname → weapon_id) ──
    //   Columns: arma_key, weapon_id, match_type, notes
    let mut arma_to_weapon: HashMap<String, String> = HashMap::new();
    for line in arma_weapon_map_tsv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 2 {
            continue;
        }
        let arma_key = fields[0].trim();
        let weapon_id = fields[1].trim();
        if arma_key.is_empty() || weapon_id.is_empty() || arma_key == "arma_key" {
            continue;
        }
        let key = arma_key.replace('\\', "\\\\").replace('\'', "\\'");
        let val = weapon_id.replace('\\', "\\\\").replace('\'', "\\'");
        // First occurrence wins (consistent with legacy behavior)
        if !arma_to_weapon.contains_key(&key) {
            arma_to_weapon.insert(key, val);
        }
    }

    // ── Load legacy ir_weapons.tsv ──
    //   Columns: model, caliber_mm, barrel_mm, twist_mm, pressure_mpa, mass_g
    let mut legacy_weapons: HashMap<String, String> = HashMap::new();
    for line in weapons_tsv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 6 {
            continue;
        }
        let model = fields[0].trim();
        if model.is_empty() || model == "model" {
            continue;
        }
        let key = model.replace('\\', "\\\\").replace('\'', "\\'");
        if legacy_weapons.contains_key(&key) {
            continue; // first occurrence wins
        }
        let cal = fmt_f64(fields[1].trim());
        let barrel = fmt_f64(fields[2].trim());
        let twist = fmt_f64(fields[3].trim());
        let pressure = fmt_f64(fields[4].trim());
        let mass = fmt_f64(fields[5].trim());
        legacy_weapons.insert(
            key.clone(),
            format!(
                "barrel_length_mm: {},\n\
                 chamber_pressure_mpa: {},\n\
                 caliber_mm: {},\n\
                 projectile_mass_g: {},\n\
                 barrel_twist_mm: {},\n",
                barrel, pressure, cal, mass, twist,
            ),
        );
    }

    // ── Combine: build IRL_WEAPONS map ──
    //   Priority: real_weapon_specs (via arma_weapon_map) > legacy_weapons
    let mut combined: HashMap<String, String> = HashMap::new();

    // Phase 1: arma_weapon_map entries resolved through real_weapon_specs
    let mut mapped_from_real = 0usize;
    for (arma_key, weapon_id) in &arma_to_weapon {
        if let Some(spec) = real_weapon_specs.get(weapon_id) {
            combined.insert(arma_key.clone(), spec.clone());
            mapped_from_real += 1;
        }
    }

    // Phase 2: legacy entries not already covered by real data
    let mut legacy_fallback = 0usize;
    for (key, spec) in &legacy_weapons {
        if !combined.contains_key(key) {
            combined.insert(key.clone(), spec.clone());
            legacy_fallback += 1;
        }
    }

    // ── Emit IRL_WEAPONS ──
    output.push_str("#[allow(clippy::excessive_precision)]\n");
    output.push_str(
        "pub(crate) static IRL_WEAPONS: phf::Map<&'static str, WeaponParams> = phf_map! {\n",
    );
    // Sort for deterministic output order
    let mut sorted_keys: Vec<&String> = combined.keys().collect();
    sorted_keys.sort();
    for key in sorted_keys {
        if let Some(body) = combined.get(key) {
            output.push_str(&format!(
                "    \"{}\" => WeaponParams {{\n{}    }},\n",
                key, body
            ));
        }
    }
    output.push_str("};\n\n");
    eprintln!(
        "build.rs: IRL_WEAPONS: {} real+mapped + {} legacy = {} total",
        mapped_from_real,
        legacy_fallback,
        combined.len()
    );

    // ── Ammo map ────────────────────────────────────────────────────────────────
    output.push_str("#[allow(clippy::excessive_precision)]\n");
    output
        .push_str("pub(crate) static IRL_AMMO: phf::Map<&'static str, AmmoParams> = phf_map! {\n");

    let mut unique_ammo: HashMap<String, String> = HashMap::new();
    for line in ammo_tsv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 6 {
            continue;
        }
        let key = fields[0].trim().replace('\\', "\\\\").replace('\'', "\\'");
        if key.is_empty() || key == "model" {
            continue;
        }
        if unique_ammo.contains_key(&key) {
            continue;
        }

        let fmt_f64 = |s: &str| -> String {
            let v: f64 = s.parse().unwrap_or(0.0);
            if v == v.floor() && v.is_finite() {
                format!("{}.0", v)
            } else {
                format!("{}", v)
            }
        };
        let diameter = fmt_f64(fields[1].trim());
        let mass = fmt_f64(fields[2].trim());
        let bc_g1 = fmt_f64(fields[3].trim());
        let bc_g7 = fmt_f64(fields[4].trim());
        let drag_raw = fields[5].trim();

        unique_ammo.insert(
            key.clone(),
            format!(
                "    \"{}\" => AmmoParams {{\n\
                 bullet_diameter_mm: {},\n\
                 projectile_mass_g: {},\n\
                 bc_g1: {},\n\
                 bc_g7: {},\n\
                 drag_model: {},\n\
                }},\n",
                key, diameter, mass, bc_g1, bc_g7, drag_raw,
            ),
        );
    }
    for entry in unique_ammo.values() {
        output.push_str(entry);
    }
    output.push_str("};\n");

    // ── Armor plates map (string values, pipe-delimited) ──────────────────────
    output.push_str(
        "\npub(crate) static I4L_ARMOR_PLATES: phf::Map<&'static str, &'static str> = phf_map! {\n",
    );

    let mut unique_armor: HashMap<String, String> = HashMap::new();
    for line in armor_tsv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 8 {
            continue;
        }
        let vehicle = fields[0].trim();
        let name = fields[1].trim();
        if vehicle.is_empty() || name.is_empty() || vehicle == "vehicle" {
            continue;
        }
        let key = format!("{}/{}", vehicle, name)
            .replace('\\', "\\\\")
            .replace('\'', "\\'");
        if unique_armor.contains_key(&key) {
            continue; // first occurrence wins
        }
        // value = material|thickness_mm|angle_deg|backing|backing_thickness_mm|backing_angle_deg
        let val = format!(
            "{}|{}|{}|{}|{}|{}",
            fields[2].trim(), // material
            fields[3].trim(), // thickness_mm
            fields[4].trim(), // angle_deg
            fields[5].trim(), // backing
            fields[6].trim(), // backing_thickness_mm
            fields[7].trim(), // backing_angle_deg
        );
        unique_armor.insert(key, val);
    }
    for (key, val) in &unique_armor {
        output.push_str(&format!("    \"{}\" => \"{}\",\n", key, val));
    }
    output.push_str("};\n");

    // ── Materials map (string values, pipe-delimited) ───────────────────────
    output.push_str(
        "\npub(crate) static I4L_MATERIALS: phf::Map<&'static str, &'static str> = phf_map! {\n",
    );

    for line in materials_tsv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 8 {
            continue;
        }
        let mat_id = fields[0].trim();
        if mat_id.is_empty() || mat_id == "material_id" {
            continue;
        }
        let key = mat_id.replace('\\', "\\\\").replace('\'', "\\'");
        // value = display_name|density_gcm3|hardness_bhn|tensile_strength_mpa|rha_equivalent|ductility|spall_coeff
        let val = format!(
            "{}|{}|{}|{}|{}|{}|{}",
            fields[1].trim(), // display_name
            fields[2].trim(), // density_gcm3
            fields[3].trim(), // hardness_bhn
            fields[4].trim(), // tensile_strength_mpa
            fields[5].trim(), // rha_equivalent
            fields[6].trim(), // ductility
            fields[7].trim(), // spall_coeff
        );
        output.push_str(&format!("    \"{}\" => \"{}\",\n", key, val));
    }
    output.push_str("};\n");

    // ── Clothing map (string values, pipe-delimited) ──────────────────────────
    output.push_str(
        "\npub(crate) static IR_CLOTHING: phf::Map<&'static str, &'static str> = phf_map! {\n",
    );

    let mut unique_clothing: HashMap<String, String> = HashMap::new();
    for line in fs::read_to_string("../data/ir_clothing.tsv")
        .unwrap_or_default()
        .lines()
    {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 11 {
            continue;
        }
        let classname = fields[0].trim();
        if classname.is_empty() || classname == "classname" {
            continue;
        }
        let key = classname.replace('\\', "\\\\").replace('\'', "\\'");
        if unique_clothing.contains_key(&key) {
            continue; // first occurrence wins
        }
        // value = item_type|clothing_category|primary_material|backing_material|thickness_mm|nij_rating|rha_mm|confidence|manufacturer|model
        let val = format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}",
            fields[1].trim(),  // item_type
            fields[2].trim(),  // clothing_category
            fields[3].trim(),  // primary_material
            fields[4].trim(),  // backing_material
            fields[5].trim(),  // thickness_mm
            fields[6].trim(),  // nij_rating
            fields[7].trim(),  // rha_mm
            fields[8].trim(),  // confidence
            fields[9].trim(),  // manufacturer
            fields[10].trim(), // model
        );
        unique_clothing.insert(key, val);
    }
    for (key, val) in &unique_clothing {
        output.push_str(&format!("    \"{}\" => \"{}\",\n", key, val));
    }
    output.push_str("};\n");

    fs::write(dest, output).unwrap();
}
