// ── Build-time PHF map generation ────────────────────────────────────────────
//
// Reads data/ir_weapons.tsv and data/ir_ammo.tsv at compile time,
// generates Rust source defining phf::Map entries for IRL weapon/ammo specs.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("generated_irl.rs");

    // Trigger rebuild if TSV files change
    println!("cargo:rerun-if-changed=../data/ir_weapons.tsv");
    println!("cargo:rerun-if-changed=../data/ir_ammo.tsv");

    let weapons_tsv =
        fs::read_to_string("../data/ir_weapons.tsv").unwrap_or_else(|_| String::new());
    let ammo_tsv = fs::read_to_string("../data/ir_ammo.tsv").unwrap_or_else(|_| String::new());

    let mut output = String::new();
    output.push_str("// auto-generated by build.rs — do not edit\n");
    output.push_str("// source: data/ir_weapons.tsv and data/ir_ammo.tsv\n\n");

    output.push_str("use phf::phf_map;\n\n");
    output.push_str("use crate::systems::ir_lookup::{WeaponParams, AmmoParams};\n\n");

    // ── Weapons map ──────────────────────────────────────────────────────────────
    output.push_str("#[allow(clippy::excessive_precision)]\n");
    output.push_str(
        "pub(crate) static IRL_WEAPONS: phf::Map<&'static str, WeaponParams> = phf_map! {\n",
    );

    // Collect unique entries by model name (first occurrence wins)
    let mut unique_weapons: HashMap<String, String> = HashMap::new();
    for line in weapons_tsv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 6 {
            continue;
        }
        let model = fields[0].trim();
        if model.is_empty() || model == "model" {
            continue;
        }
        // Skip duplicate keys (keep first occurrence)
        let key = model.replace('\\', "\\\\").replace('\'', "\\'");
        if unique_weapons.contains_key(&key) {
            continue;
        }

        let fmt_f64 = |s: &str| -> String {
            let v: f64 = s.parse().unwrap_or(0.0);
            if v == v.floor() && v.is_finite() {
                format!("{}.0", v)
            } else {
                format!("{}", v)
            }
        };
        let cal = fmt_f64(fields[1].trim());
        let barrel = fmt_f64(fields[2].trim());
        let twist = fmt_f64(fields[3].trim());
        let pressure = fmt_f64(fields[4].trim());
        let mass = fmt_f64(fields[5].trim());

        unique_weapons.insert(
            key.clone(),
            format!(
                "    \"{}\" => WeaponParams {{\n\
                 barrel_length_mm: {},\n\
                 chamber_pressure_mpa: {},\n\
                 caliber_mm: {},\n\
                 projectile_mass_g: {},\n\
                 barrel_twist_mm: {},\n\
                }},\n",
                key, barrel, pressure, cal, mass, twist,
            ),
        );
    }
    for entry in unique_weapons.values() {
        output.push_str(entry);
    }
    output.push_str("};\n\n");

    // ── Ammo map ────────────────────────────────────────────────────────────────
    output.push_str("#[allow(clippy::excessive_precision)]\n");
    output
        .push_str("pub(crate) static IRL_AMMO: phf::Map<&'static str, AmmoParams> = phf_map! {\n");

    let mut unique_ammo: HashMap<String, String> = HashMap::new();
    for line in ammo_tsv.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 6 {
            continue;
        }
        let key = fields[0].trim().replace('\\', "\\\\").replace('\'', "\\'");
        if key.is_empty() || key == "model" {
            continue;
        }
        if unique_ammo.contains_key(&key) {
            continue;
        }

        let fmt_f64 = |s: &str| -> String {
            let v: f64 = s.parse().unwrap_or(0.0);
            if v == v.floor() && v.is_finite() {
                format!("{}.0", v)
            } else {
                format!("{}", v)
            }
        };
        let diameter = fmt_f64(fields[1].trim());
        let mass = fmt_f64(fields[2].trim());
        let bc_g1 = fmt_f64(fields[3].trim());
        let bc_g7 = fmt_f64(fields[4].trim());
        let drag_raw = fields[5].trim();

        unique_ammo.insert(
            key.clone(),
            format!(
                "    \"{}\" => AmmoParams {{\n\
                 bullet_diameter_mm: {},\n\
                 projectile_mass_g: {},\n\
                 bc_g1: {},\n\
                 bc_g7: {},\n\
                 drag_model: {},\n\
                }},\n",
                key, diameter, mass, bc_g1, bc_g7, drag_raw,
            ),
        );
    }
    for entry in unique_ammo.values() {
        output.push_str(entry);
    }
    output.push_str("};\n");

    fs::write(dest, output).unwrap();
}
