name = "Advanced Ballistics Extension"
prefix = "abe"
mainprefix = "z"
[version]
major = 0
minor = 1
patch = 0
git_hash = 0

[files]
include = [
    "mod.cpp",
    "ext/abe_ballistics_ext.dll",
    "ext/libabe_ballistics_ext.so",
    "data/weapons/**",
    "data/ammo/**",
    "data/armor/**",
]
exclude = [
    "*.psd",
    "*.blend",
]

[hemtt.build]
optional_mod_folders = false

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
]

[hemtt.launch.headless]
workshop = [
    "450814997", # CBA_A3
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-world=empty",
    "-name=abe_test",
    "-config=.hemtt/server.cfg",
]
executable = "arma3server_x64"

[hemtt.launch.test]
extends = "default"
workshop = [
    "450814997", # CBA_A3
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-name=abe_test",
    "-init=playMission 'abe_headless_test.VR'",
]
